-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		ALL
-- // MODULE:			TAG x FORMA
-- // OPERATION:		SP
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX DE LA ROSA			
-- // CREATION DATE:	20200320
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO

-- //////////////////////////////////////////////////////////////
-- SELECT * FROM SISTEMA_TAG
-- SELECT * FROM GRUPO_TAG
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SISTEMA_TAG]') AND type in (N'U'))
	DROP TABLE [dbo].[SISTEMA_TAG]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GRUPO_TAG]') AND type in (N'U'))
	DROP TABLE [dbo].[GRUPO_TAG]
GO



-- //////////////////////////////////////////////////////////////
-- // GRUPO_TAG
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[GRUPO_TAG] (
	[K_GRUPO_TAG]	[INT] NOT NULL,
	[D_GRUPO_TAG]	[VARCHAR] (100) NOT NULL,
	[S_GRUPO_TAG]	[VARCHAR] (10) NOT NULL,
	[O_GRUPO_TAG]	[INT] NOT NULL,
	[C_GRUPO_TAG]	[VARCHAR] (255) NOT NULL,
	[L_GRUPO_TAG]	[INT] NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////////////

ALTER TABLE [dbo].[GRUPO_TAG]
	ADD CONSTRAINT [PK_GRUPO_TAG]
		PRIMARY KEY CLUSTERED ([K_GRUPO_TAG])
GO

CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_GRUPO_TAG_01_DESCRIPCION] 
	   ON [dbo].[GRUPO_TAG] ( [D_GRUPO_TAG] )
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_GRUPO_TAG]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_GRUPO_TAG]
GO

CREATE PROCEDURE [dbo].[PG_CI_GRUPO_TAG]
	@PP_K_GRUPO_TAG		[INT],
	@PP_D_GRUPO_TAG		[VARCHAR](100),
	@PP_S_GRUPO_TAG		[VARCHAR](10),
	@PP_O_GRUPO_TAG		[INT],
	@PP_C_GRUPO_TAG		[VARCHAR](255),
	@PP_L_GRUPO_TAG		[INT]
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_GRUPO_TAG
							FROM	GRUPO_TAG
							WHERE	K_GRUPO_TAG=@PP_K_GRUPO_TAG
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO GRUPO_TAG
			(	K_GRUPO_TAG,			D_GRUPO_TAG, 
				S_GRUPO_TAG,			O_GRUPO_TAG,
				C_GRUPO_TAG,
				L_GRUPO_TAG			)		
		VALUES	
			(	@PP_K_GRUPO_TAG,		@PP_D_GRUPO_TAG,	
				@PP_S_GRUPO_TAG,		@PP_O_GRUPO_TAG,
				@PP_C_GRUPO_TAG,
				@PP_L_GRUPO_TAG		)
	ELSE
		UPDATE	GRUPO_TAG
		SET		D_GRUPO_TAG	= @PP_D_GRUPO_TAG,	
				S_GRUPO_TAG	= @PP_S_GRUPO_TAG,			
				O_GRUPO_TAG	= @PP_O_GRUPO_TAG,
				C_GRUPO_TAG	= @PP_C_GRUPO_TAG,
				L_GRUPO_TAG	= @PP_L_GRUPO_TAG	
		WHERE	K_GRUPO_TAG=@PP_K_GRUPO_TAG
	-- =========================================================
GO

SET NOCOUNT ON
-- ===============================================
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 00, '(SIN-GRUPO)',		'( S/G )',	00 , '#00 // (SIN-GRUPO)'	, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 10, 'CALIDAD',			'CALID',	10 , '#10 // CALID'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 20, 'FINAL',			'FINAL',	20 , '#20 // FINAL'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 30, 'FINANZAS',			'FINZS',	30 , '#30 // FINZS'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 40, 'GENERAL',			'GNRAL',	40 , '#40 // GNRAL'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 50, 'INGENIERIA',		'INGEN',	50 , '#50 // INGEN'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 60, 'MATERIALES',		'MATER',	60 , '#60 // MATER'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 70, 'PRODUCCION',		'PRODU',	70 , '#70 // PRODU'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 80, 'RECURSOS_HUMANOS',	'RHUMA',	80 , '#80 // RHUMA'			, 1
EXECUTE [dbo].[PG_CI_GRUPO_TAG] 90, 'SISTEMAS',			'SISTM',	90 , '#90 // SISTM'			, 1

	-- ===============================================
GO



-- //////////////////////////////////////////////////////////////
-- // SISTEMA_TAG
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[SISTEMA_TAG] (
	[K_SISTEMA_TAG]	[INT] NOT NULL,
	[D_SISTEMA_TAG]	[VARCHAR] (100) NOT NULL,
	[S_SISTEMA_TAG]	[VARCHAR] (10) NOT NULL DEFAULT '',
	[O_SISTEMA_TAG]	[INT] NOT NULL DEFAULT 0,
	[C_SISTEMA_TAG]	[VARCHAR] (255) NOT NULL DEFAULT '',
	[L_SISTEMA_TAG]	[INT] NOT NULL DEFAULT 1,
	-- ========================================
	[K_GRUPO_TAG]	[INT] NOT NULL DEFAULT 0,
	[L_FORMA_TAG]	[INT] NOT NULL DEFAULT 1
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////////////

ALTER TABLE [dbo].[SISTEMA_TAG]
	ADD CONSTRAINT [PK_SISTEMA_TAG]
		PRIMARY KEY CLUSTERED ([K_SISTEMA_TAG])
GO

CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_SISTEMA_TAG_01_DESCRIPCION] 
	   ON [dbo].[SISTEMA_TAG] ( [D_SISTEMA_TAG] )
GO
-- //////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[SISTEMA_TAG] ADD 
	CONSTRAINT [FK_SISTEMA_TAG_01] 
		FOREIGN KEY ( [K_GRUPO_TAG] ) 
		REFERENCES [dbo].[GRUPO_TAG] ( [K_GRUPO_TAG] )
GO



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SISTEMA_TAG]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_SISTEMA_TAG]
GO


CREATE PROCEDURE [dbo].[PG_CI_SISTEMA_TAG]
	@PP_K_USUARIO_EXE		[INT],
	-- ========================================
	@PP_K_SISTEMA_TAG		[INT],
	@PP_D_SISTEMA_TAG		[VARCHAR](100),
	@PP_S_SISTEMA_TAG		[VARCHAR](10),
	@PP_O_SISTEMA_TAG		[INT],
	@PP_C_SISTEMA_TAG		[VARCHAR](255),
	@PP_L_SISTEMA_TAG		[INT],
	-- ===============================
	@PP_K_GRUPO_TAG			[INT],
	@PP_L_FORMA_TAG			[INT]
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT
	SELECT	@VP_K_EXISTE =	K_SISTEMA_TAG
							FROM	SISTEMA_TAG
							WHERE	K_SISTEMA_TAG=@PP_K_SISTEMA_TAG
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO SISTEMA_TAG
			(	K_SISTEMA_TAG,			D_SISTEMA_TAG, 
				S_SISTEMA_TAG,			O_SISTEMA_TAG,
				C_SISTEMA_TAG,
				L_SISTEMA_TAG,			K_GRUPO_TAG	,
				L_FORMA_TAG				)
		VALUES	
			(	@PP_K_SISTEMA_TAG,		@PP_D_SISTEMA_TAG,	
				@PP_S_SISTEMA_TAG,		@PP_O_SISTEMA_TAG,
				@PP_C_SISTEMA_TAG,
				@PP_L_SISTEMA_TAG,		@PP_K_GRUPO_TAG	,
				@PP_L_FORMA_TAG			)
	ELSE
		UPDATE	SISTEMA_TAG
		SET		D_SISTEMA_TAG	= @PP_D_SISTEMA_TAG,	
				S_SISTEMA_TAG	= @PP_S_SISTEMA_TAG,			
				O_SISTEMA_TAG	= @PP_O_SISTEMA_TAG,
				C_SISTEMA_TAG	= @PP_C_SISTEMA_TAG,
				L_SISTEMA_TAG	= @PP_L_SISTEMA_TAG,
				K_GRUPO_TAG		= @PP_K_GRUPO_TAG,
				L_FORMA_TAG		= @PP_L_FORMA_TAG
		WHERE	K_SISTEMA_TAG=@PP_K_SISTEMA_TAG
	-- =========================================================
GO


SET NOCOUNT ON
-- ===============================================
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 0, '(NO-SISTEMA)', '( N/S )' , 0 , '#0 // (NO-SISTEMA)' , 1,0,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 1, 'PRODUCTION REPORT', '#001' , 1 , '#1 // PRODUCTION REPORT' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 2, 'SUPERVISORS', '#002' , 2 , '#2 // SUPERVISORS' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 3, 'PRODUCTION', '#003' , 3 , '#3 // PRODUCTION' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 4, 'REJECTS', '#004' , 4 , '#4 // REJECTS' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 5, 'PLANNING SCREEN', '#005' , 5 , '#5 // PLANNING SCREEN' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 6, 'TRANSACTIONS', '#006' , 6 , '#6 // TRANSACTIONS' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 7, 'HIDES SCANNER', '#007' , 7 , '#7 // HIDES SCANNER' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 8, 'PACKING SLIP', '#008' , 8 , '#8 // PACKING SLIP' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 9, 'TRANSFER MCT TO MFP', '#009' , 9 , '#9 // TRANSFER MCT TO MFP' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 10, 'MFP INVENTORY', '#010' , 10 , '#10 // MFP INVENTORY' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 11, 'LABELS', '#011' , 11 , '#11 // LABELS' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 12, 'HIDE LABELS', '#012' , 12 , '#12 // HIDE LABELS' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 13, 'PPMS', '#013' , 13 , '#13 // PPMS' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 14, 'LOAD RELEASE', '#014' , 14 , '#14 // LOAD RELEASE' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 15, 'EDI WEEKLY RPT', '#015' , 15 , '#15 // EDI WEEKLY RPT' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 16, 'DAILY INVENTORY', '#016' , 16 , '#16 // DAILY INVENTORY' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 17, 'HIDES ALLOCATION', '#017' , 17 , '#17 // HIDES ALLOCATION' , 1,40,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 18, 'HUMAN RESOURCES', '#018' , 18 , '#18 // HUMAN RESOURCES' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 19, 'STOCK STATUS', '#019' , 19 , '#19 // STOCK STATUS' , 1,40,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 20, 'EXCEL PRODUCTION REPORT', '#020' , 20 , '\\10.1.1.5\documents\PEARL\Reportes\Excel Production Report.xlsm' , 1,70,0
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 21, 'BELL CURVE', '#021' , 21 , '\\10.1.1.5\documents\PEARL\Reportes\Bell_Curve_Report.xls' , 1,40,0
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 22, 'TRANSACTION REPORT', '#022' , 22 , '#22 // TRANSACTION REPORT' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 23, 'CERTIFICATION REPORT', '#023' , 23 , '#23 // CERTIFICATION REPORT' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 24, 'FOLIOS INVENTORY', '#024' , 24 , '#24 // FOLIOS INVENTORY' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 25, 'QUALITY REJECTS', '#025' , 25 , '#25 // QUALITY REJECTS' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 26, 'PACKING MACOLA', '#026' , 26 , '#26 // PACKING MACOLA' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 27, 'TAGS', '#27' , 27 , '#027 // TAGS' , 1,30,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 28, 'SALES BY CUST', '#028' , 28 , '#28 // SALES BY CUST' , 1,30,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 29, 'POLIZA DE NOMINA', '#029' , 29 , '#29 // POLIZA DE NOMINA' , 1,30,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 30, 'HISTORY BY JOB NO', '#030' , 30 , '#30 // HISTORY BY JOB NO' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 31, 'PATTERN LABELS', '#031' , 31 , '#31 // PATTERN LABELS' , 1,90,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 32, 'CUMULATIVE REPORT', '#032' , 32 , '#32 // CUMULATIVE REPORT' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 33, 'INCOMING INSPECTION', '#033' , 33 , '#33 // INCOMING INSPECTION' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 34, 'STATUS DE ORDENES', '#034' , 34 , '#34 // STATUS DE ORDENES' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 35, 'COLORS MANT', '#035' , 35 , '#35 // COLORS MANT' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 36, 'UPDATE TARGET', '#036' , 36 , '#36 // UPDATE TARGET' , 1,40,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 37, 'LOT COMP', '#037' , 37 , '#37 // LOT COMP' , 1,10,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 38, 'ENGINEERING SCREEN', '#038' , 38 , '#38 // ENGINEERING SCREEN' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 39, 'PROD CATEGORY', '#039' , 39 , '#39 // PROD CATEGORY' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 40, 'ITEM MASTER', '#040' , 40 , '#40 // ITEM MASTER' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 41, 'KIT MASTER', '#041' , 41 , '#41 // KIT MASTER' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 42, 'ADD LOCATION', '#042' , 42 , '#42 // ADD LOCATION' , 1,40,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 43, 'BILLING', '#043' , 43 , '#43 // BILLING' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 44, 'TRANS FOLIOS', '#044' , 44 , '#44 // TRANS FOLIOS' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 45, 'RE-PRINT INVOICE', '#045' , 45 , '#45 // RE-PRINT INVOICE' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 46, 'CUM REPORT', '#046' , 46 , '#46 // CUM REPORT' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 47, 'REPORTE DE DEFECTOS', '#047' , 47 , '#47 // REPORTE DE DEFECTOS' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 48, 'LOT YIELD', '#048' , 48 , '#48 // LOT YIELD' , 1,70,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 49, 'LOT TRACK', '#049' , 49 , '#49 // LOT TRACK' , 1,40,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 50, 'SALIDAS DE INV', '#050' , 50 , '#50 // SALIDAS DE INV' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 51, 'USUARIOS', '#051' , 51 , '#51 // USUARIOS' , 1,90,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 52, 'MTTO PREVENTIVO', '#052' , 52 , '#52 // MTTO PREVENTIVO' , 1,90,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 53, 'EQUIPOS', '#053' , 53 , '#53 // EQUIPOS' , 1,90,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 54, 'BAJAS', '#054' , 54 , '#54 // BAJAS' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 55, 'CAPACITACION', '#055' , 55 , '#55 // CAPACITACION' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 56, 'HIDE LABELS JL', '#056' , 56 , '#56 // HIDE LABELS JL' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 57, 'TONERS', '#057' , 57 , '#57 // TONERS' , 1,90,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 58, 'CERRAR KITS', '#058' , 58 , '#58 // CERRAR KITS' , 1,20,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 59, 'AUSENTISMO', '#059' , 59 , '#59 // AUSENTISMO' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 60, 'REPORTE', '#060' , 60 , '#60 // REPORTE' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 61, 'COMPRAS', '#061' , 61 , '#61 // COMPRAS' , 1,30,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 62, 'IMPORT HIDES', '#062' , 62 , '#62 // IMPORT HIDES' , 1,60,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 63, 'HEAD COUNT', '#063' , 63 , '#63 // HEAD COUNT' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 64, 'SALES REPORT', '#064' , 64 , '#64 // SALES REPORT' , 1,30,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 65, 'FINGERPRINT', '#065' , 65 , '#65 // FINGERPRINT' , 1,80,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 66, 'CUSTOMERS', '#066' , 66 , '#66 // CUSTOMERS' , 1,50,1
EXECUTE [DBO].[PG_CI_SISTEMA_TAG] 139, 67, 'COTIZACIONES', '#067' , 67 , '#67 // COTIZACIONES' , 1,50,1
	-- ===============================================
GO

-- ////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////

