-- =============================================
-- Author:		<ALEX DE LA ROSA>
-- Create date: <2019-03-25>
-- Description:	<Verificar si el Usuario tiene palabras inconvenientes o existe otro registro igual>
-- =============================================

USE [BD_GENERAL]
GO

CREATE FUNCTION [dbo].[USER_INCONVENIENT_OR_EXIST]
	(	@PP_K_USUARIO INT,
		@PP_D_USUARIO NVARCHAR(MAX)
	)
  RETURNS INT
  AS
	BEGIN
	DECLARE @VP_EXISTE INT
		IF	@PP_D_USUARIO LIKE ('%ANAL%') OR	@PP_D_USUARIO LIKE ('%BUEI%') OR	@PP_D_USUARIO LIKE ('%BUEY%')  
		OR	@PP_D_USUARIO LIKE ('%CACA%') OR	@PP_D_USUARIO LIKE ('%CACO%') OR	@PP_D_USUARIO LIKE ('%CAGA%')  
		OR	@PP_D_USUARIO LIKE ('%CAGO%') OR	@PP_D_USUARIO LIKE ('%CAKA%') OR	@PP_D_USUARIO LIKE ('%CAKO%')  
		OR	@PP_D_USUARIO LIKE ('%COGE%') OR	@PP_D_USUARIO LIKE ('%COJA%') OR	@PP_D_USUARIO LIKE ('%COJE%')  
		OR	@PP_D_USUARIO LIKE ('%COJI%') OR	@PP_D_USUARIO LIKE ('%COJO%') OR	@PP_D_USUARIO LIKE ('%CULA%')  
		OR	@PP_D_USUARIO LIKE ('%CULO%') OR	@PP_D_USUARIO LIKE ('%FETO%') OR	@PP_D_USUARIO LIKE ('%GUEY%')  
		OR	@PP_D_USUARIO LIKE ('%JOTO%') OR	@PP_D_USUARIO LIKE ('%KACA%') OR	@PP_D_USUARIO LIKE ('%KACO%')  
		OR	@PP_D_USUARIO LIKE ('%KAGA%') OR	@PP_D_USUARIO LIKE ('%KAGO%') OR	@PP_D_USUARIO LIKE ('%KOGE%')  
		OR	@PP_D_USUARIO LIKE ('%KOJO%') OR	@PP_D_USUARIO LIKE ('%KAKA%') OR	@PP_D_USUARIO LIKE ('%KULO%')  
		OR	@PP_D_USUARIO LIKE ('%MAME%') OR	@PP_D_USUARIO LIKE ('%MAMO%') OR	@PP_D_USUARIO LIKE ('%MEAR%')  
		OR	@PP_D_USUARIO LIKE ('%MEAS%') OR	@PP_D_USUARIO LIKE ('%MEON%') OR	@PP_D_USUARIO LIKE ('%MIAR%')  
		OR	@PP_D_USUARIO LIKE ('%MION%') OR	@PP_D_USUARIO LIKE ('%MOCO%') OR	@PP_D_USUARIO LIKE ('%MULA%')  
		OR	@PP_D_USUARIO LIKE ('%NACA%') OR	@PP_D_USUARIO LIKE ('%NACO%') OR	@PP_D_USUARIO LIKE ('%PEDA%')  
		OR	@PP_D_USUARIO LIKE ('%PEDO%') OR	@PP_D_USUARIO LIKE ('%PENE%') OR	@PP_D_USUARIO LIKE ('%PUTA%')  
		OR	@PP_D_USUARIO LIKE ('%PUTO%') OR	@PP_D_USUARIO LIKE ('%QULO%') OR	@PP_D_USUARIO LIKE ('%RATA%')  
		OR	@PP_D_USUARIO LIKE ('%RUIN%') OR	@PP_D_USUARIO LIKE ('%SEXO%')
					BEGIN
						SET @VP_EXISTE= 1
					END
				ELSE
					BEGIN
						SET @VP_EXISTE= 0
					END

					RETURN @VP_EXISTE
	END;