-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[BD_GENERAL]
-- // MODULO:			[ACCIONES EN FORMAS]
-- // OPERACION:		LIBERACION / STORED PROCEDURES
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	26/JUN/2020
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SISTEMA_CONTROL_PERMISO]') AND type in (N'U'))
	DROP TABLE [dbo].[SISTEMA_CONTROL_PERMISO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SISTEMA_CONTROL]') AND type in (N'U'))
	DROP TABLE [dbo].[SISTEMA_CONTROL]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SUB_SISTEMA_TAG]') AND type in (N'U'))
	DROP TABLE [dbo].[SUB_SISTEMA_TAG]
GO

-- //////////////////////////////////////////////////////////////
-- // SUB_SISTEMA_TAG
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[SUB_SISTEMA_TAG] (
	[K_SUB_SISTEMA_TAG]			[INT]			NOT NULL,
	-- =================================	
	[D_SUB_SISTEMA_TAG]			VARCHAR(100)	NOT NULL
	-- =================================	
)ON [PRIMARY]	
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[SUB_SISTEMA_TAG]
	ADD CONSTRAINT [PK_SUB_SISTEMA_TAG]
		PRIMARY KEY CLUSTERED ([K_SUB_SISTEMA_TAG])
GO
-- //////////////////////////////////////////////////////////////	
--GO
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SUB_SISTEMA_TAG]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_SUB_SISTEMA_TAG]
GO
CREATE PROCEDURE [dbo].[PG_CI_SUB_SISTEMA_TAG]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	-- ========================================
	@PP_K_SUB_SISTEMA_TAG			INT,
	@PP_D_SUB_SISTEMA_TAG			VARCHAR(100)
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_SUB_SISTEMA_TAG
							FROM	SUB_SISTEMA_TAG
							WHERE	K_SUB_SISTEMA_TAG=@PP_K_SUB_SISTEMA_TAG
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO SUB_SISTEMA_TAG	
			(	K_SUB_SISTEMA_TAG,	
				D_SUB_SISTEMA_TAG	)		
		VALUES	
			(	@PP_K_SUB_SISTEMA_TAG,				
				@PP_D_SUB_SISTEMA_TAG	)
	ELSE
		UPDATE	SUB_SISTEMA_TAG
			SET	D_SUB_SISTEMA_TAG			= @PP_D_SUB_SISTEMA_TAG
		WHERE	K_SUB_SISTEMA_TAG=@PP_K_SUB_SISTEMA_TAG

	-- =========================================================
GO

-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- AQUI SE GREGAN LAS FORMAS DONDE SE APLICARAN LOS PERMISOS DEL OBJETO
-- ===============================================
-- ===============================================
---- ===================FORMA frmLots (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 1,	'frmLots'

---- ===================FORMA frmHides (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 2,	'frmHides'

---- ===================FORMA FO_PO_REVIEW (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 3,	'FO_PO_REVIEW'

---- ===================FORMA FO_PURCHASE_ORDER (DEPENDE DE OTRA)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 4,	'FO_PURCHASE_ORDER'

---- ===================FORMA FO_INSPECCION_MATERIAL (DEPENDE DE OTRA)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 5,	'FO_AUTORIZAR_INSPECCION_MATERIAL'
-- ===============================================

---- ===================FORMA FO_PRINT_PO (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 6,	'FO_PRINT_PO'


---- ===================FORMA FO_INSPECCION_PIEL (DEPENDE DE OTRA)============================
EXECUTE [dbo].[PG_CI_SUB_SISTEMA_TAG] 0, 0, 7,	'FO_AUTORIZAR_INSPECCION_PIEL'
-- ===============================================

GO
-- ===============================================
--IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SUB_SISTEMA_TAG]') AND type in (N'P', N'PC'))
--	DROP PROCEDURE [dbo].[PG_CI_SUB_SISTEMA_TAG]
--GO

-- //////////////////////////////////////////////////////////////
-- // SISTEMA_CONTROL
-- //////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[SISTEMA_CONTROL] (
	[K_SISTEMA_CONTROL]			[INT]			NOT NULL,
	-- =================================	
	[K_SISTEMA_TAG]				INT				NOT NULL,	
	[D_SISTEMA_CONTROL]			VARCHAR(100)	NOT NULL
	-- =================================	
)ON [PRIMARY]	
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[SISTEMA_CONTROL]
	ADD CONSTRAINT [PK_SISTEMA_CONTROL]
		PRIMARY KEY CLUSTERED ([K_SISTEMA_CONTROL])
GO
-- //////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[SISTEMA_CONTROL] ADD 
	CONSTRAINT [FK_SISTEMA_CONTROL_01]  
		FOREIGN KEY ([K_SISTEMA_TAG]) 
		REFERENCES [dbo].[SISTEMA_TAG] ([K_SISTEMA_TAG])
	
GO
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SISTEMA_CONTROL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL]
GO
CREATE PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	-- ========================================
	@PP_K_SISTEMA_CONTROL			INT,
	@PP_K_SISTEMA_TAG				INT,
	@PP_D_SISTEMA_CONTROL			VARCHAR(100)
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_SISTEMA_CONTROL
							FROM	SISTEMA_CONTROL
							WHERE	K_SISTEMA_CONTROL=@PP_K_SISTEMA_CONTROL
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO SISTEMA_CONTROL	
			(	K_SISTEMA_CONTROL,					K_SISTEMA_TAG,		
				D_SISTEMA_CONTROL	)		
		VALUES	
			(	@PP_K_SISTEMA_CONTROL,				@PP_K_SISTEMA_TAG,
				@PP_D_SISTEMA_CONTROL	)
	ELSE
		UPDATE	SISTEMA_CONTROL
		SET		K_SISTEMA_TAG				= @PP_K_SISTEMA_TAG,
				D_SISTEMA_CONTROL			= @PP_D_SISTEMA_CONTROL
		WHERE	K_SISTEMA_CONTROL=@PP_K_SISTEMA_CONTROL
	-- =========================================================
GO

-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- AQUI SE LE AGREGAN LOS OBJETOS Y SE RELACIONAN CON LA FORMA PREVIAMENTE INSERTADA.
-- ===============================================
-- ===============================================
/*
use BD_GENERAL
SELECT * FROM SISTEMA_TAG WHERE D_SISTEMA_TAG = 'FO_PACKING'
select * from SISTEMA_CONTROL
SELECT * FROM USUARIO_PEARL WHERE K_USUARIO_TIPO IN (10,20,40,50) 
SELECT * FROM USUARIO_TIPO
SELECT * FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 6
WHERE K_SISTEMA_TAG = 32
AND K_USUARIO_PEARL  IN (SELECT K_USUARIO_PEARL FROM USUARIO_PEARL WHERE k_USUARIO_TIPO  IN (10,20,40,50) )

SELECT * FROM USUARIO_PEARL 
WHERE K_USUARIO_TIPO IN (10,20,40,50) 
AND K_USUARIO_PEARL IN (SELECT K_USUARIO_PEARL FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 6)
*/
-- ===================FORMA FoliosV2============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 1, 47,	'BT_ISSUE_OUT'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 2, 47,	'GB_QC_DETALLADO'

-- ===================FORMA frmLots (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 20, 1,	'cmdDetails'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 21, 1,	'cmdSave'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 22, 1,	'TextBox3'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 23, 1,	'Button1'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 24, 1,	'cmdCBackout'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 25, 1,	'cmdChk'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 26, 1,	'BTN_CERRAR_ORDEN'

-- ===================FORMA Facturacion============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 30, 46,	'Button13'

-- ===================FORMA InvD============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 40, 16,	'GroupBox3'

-- ===================FORMA eng_main============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 50, 41,	'BT_UNLOCK'

-- ===================FORMA Planning============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 60, 5,	'BT_ORDEN_ELIMINAR'

-- ===================FORMA HorseDetail============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 70, 65,	'BT_Import'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 71, 65,	'BT_Transfer2MHI'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 72, 65,	'BT_Processed'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 73, 65,	'BT_Transfer2MRD' 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 74, 65,	'BTN_IMPORT_MANUAL'

-- ===================FORMA frmHides  (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 80, 2,	'cmdSave'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 81, 2,	'TextBox3'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 82, 2,	'Button1'

-- ===================FORMA PatternsDatabase============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 90, 32,	'Button1'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 91, 32,	'Button2'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 92, 32,	'Button3'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 93, 32,	'Button4'
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 94, 32,	'Button6'

-- ===================FORMA Transferencias============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 100, 6,	'ComboBox1'

-- ===================FORMA FO_PO_REVIEW - PO ========================PARTE#1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 110, 3,	'BT_PRINT_PO'				-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 111, 3,	'PN_MANAGEMENT_VENDOR'		-- SE ENCUENTRA EN LA FORMA DEL MENÚ SE AGREGA AQUÍ PARA NO AGRANDAR LA TABLA.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 112, 3,	'CH_L_FINANCES'				-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 113, 3,	'BT_DATE_RECEIVED'			-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 114, 3,	'BT_ITEM_RECEIVED'			-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 115, 3,	'BT_VER_REPORTE'					-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 116, 3,	'CB_LI_FILTRO_ORDENES_COMPLETAS'	-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 117, 3,	'TB_TAX_RATE'				-- PARA PODER EDITAR EL IVA EN LA AUTORIZACIÓN. SUBSITEMA SE ENVÍA [#1] EN EL FRONT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 118, 3,	'VER_REPORTE_PRODUCTIVO'	-- PARA VER EL REPORTE BORRADOR O PRODUCTIVO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 119, 3,	'BT_CANCEL_PO'				-- PARA CANCELAR ORDENES DE COMPRA
-- ===================FORMA FO_PURCHASE_ORDER ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 120, 4,	'CH_IS_BLANKET_PO'			-- CHECK PARA ESTABLECER QUIEN REALIZARÁ BLANKET PO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 121, 4,	'CH_EDIT_PO_DEPTS'			-- CHECK PARA PODER EDITAR PO YA AUTORIZADA.

-- ===================FORMA FO_PO_REVIEW - PO ========================PARTE#2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 131, 3,	'BT_PO_PAYMENT'				-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT

-- ===================FORMA FO_PRINT_PO - PO ========================PARTE#1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 140, 6,	'CRV_PO.ShowPrintButton'	-- SUBSITEMA SE ENVÍA [#1] EN EL FRONT

-- ===================FORMA FO_AUTORIZAR_INSPECCION_MATERIAL ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 150, 5,	'BT_EDIT'					-- BOTON PARA AUTORIZAR O RECHAZAR INSPECCION.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 151, 5,	'BTN_GUARDAR_INSPECCION'	-- BOTON PARA GUARDAR INSPECCION MODIFICADA.

-- ===================FORMA FO_AUTORIZAR_INSPECCION_PIEL ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 160, 7,	'BT_EDIT'					-- BOTON PARA AUTORIZAR O RECHAZAR INSPECCION.
--EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 151, 5,	'BTN_GUARDAR_INSPECCION'	-- BOTON PARA GUARDAR INSPECCION MODIFICADA.

-- ===================FORMA FO_PACKING ADMINISTRACION DE INVENTARIO_EMBARQUE ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 170, 85,	'BTN_REIMPRIMIR_PACKING_INVOICE' -- BOTON PARA REGENERAR EL PACKING/INVOICE EN PDF.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 171, 85,	'BTN_CAMBIAR_ESTATUS'			-- BOTON PARA ENVIAR MATERIAL A INVENTARIO/CALIDAD.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 172, 85,	'TC_PACK_INV'					-- TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 173, 85,	'BTN_VER_ORDEN_FACTURACION'		-- BOTON BTN_VER_ORDEN_FACTURACION.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 174, 85,	'BTN_ADMINISTRAR_FACTURA'		-- BOTON BTN_ADMINISTRAR_FACTURA.

-- ===================			FORMA SupMat		========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 180, 93,	'DG_LISTING_ORDENES_PENDIENTES' -- EVITA QUE USUARIOS QUE NO SEAN DE MATERIALES PUEDAN ASIGNAR ORDENES.

-- ===================			FORMA PLANNING		========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL] 0, 0, 200, 99,	'BT_EDIT' -- BOTON EDITAR ORDEN

-- ===============================================
SET NOCOUNT OFF
GO
-- ===============================================
--IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SISTEMA_CONTROL]') AND type in (N'P', N'PC'))
--	DROP PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL]
--GO

-- //////////////////////////////////////////////////////////////
-- // SISTEMA_CONTROL
-- //////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[SISTEMA_CONTROL_PERMISO] (
	[K_SISTEMA_CONTROL_PERMISO]			[INT]		NOT NULL,
	-- =================================	
	[K_SISTEMA_CONTROL]				INT				NOT NULL,	
	[K_USUARIO]						INT				NOT NULL
	-- =================================	
)ON [PRIMARY]	
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[SISTEMA_CONTROL_PERMISO]
	ADD CONSTRAINT [PK_SISTEMA_CONTROL_PERMISO]
		PRIMARY KEY CLUSTERED ([K_SISTEMA_CONTROL_PERMISO])
GO
-- //////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[SISTEMA_CONTROL_PERMISO] ADD 
	CONSTRAINT [FK_SISTEMA_CONTROL_PERMISO_01]  
		FOREIGN KEY ([K_USUARIO]) 
		REFERENCES [dbo].[USUARIO_PEARL] ([K_USUARIO_PEARL])	
GO
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SISTEMA_CONTROL_PERMISO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO]
GO
CREATE PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	-- ========================================
	@PP_K_SISTEMA_CONTROL_PERMISO	INT,
	@PP_K_SISTEMA_CONTROL			INT,
	@PP_K_USUARIO					VARCHAR(100)
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_SISTEMA_CONTROL_PERMISO
							FROM	SISTEMA_CONTROL_PERMISO
							WHERE	K_SISTEMA_CONTROL_PERMISO=@PP_K_SISTEMA_CONTROL_PERMISO
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO SISTEMA_CONTROL_PERMISO	
			(	K_SISTEMA_CONTROL_PERMISO,					K_SISTEMA_CONTROL,
				K_USUARIO	
					)		
		VALUES	
			(	@PP_K_SISTEMA_CONTROL_PERMISO,				@PP_K_SISTEMA_CONTROL,
				@PP_K_USUARIO	)
	ELSE
		UPDATE	SISTEMA_CONTROL_PERMISO
		SET		K_SISTEMA_CONTROL			= @PP_K_SISTEMA_CONTROL,
				K_USUARIO	= @PP_K_USUARIO
		WHERE	K_SISTEMA_CONTROL_PERMISO=@PP_K_SISTEMA_CONTROL_PERMISO
	-- =========================================================
GO

-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- AQUI SE RELACIONAN LOS OBJETOS CON LOS USUARIOS QUE PODRÁN VISUALIZARLOS
-- ===============================================
-- ===============================================
/*
use BD_GENERAL
select * from sistema_tag where d_sistema_tag = 'eng_main'
select * from SISTEMA_CONTROL
select * from SISTEMA_CONTROL_PERMISO WHERE K_SISTEMA_CONTROL = 50
SELECT * FROM USUARIO_PEARL WHERE K_USARIO--k_USUARIO_TIPO = 70 --K_USUARIO_PEARL IN (144,41,139)
SELECT * FROM USUARIO_TIPO

SELECT  K_USUARIO_TIPO AS TIPO ,* FROM USUARIO_PEARL 
WHERE K_USUARIO_TIPO IN (10) 
AND K_USUARIO_PEARL IN (SELECT K_USUARIO_PEARL FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 41)

SELECT * FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 41
*/
-- ===================FORMA FoliosV2============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 1, 1,	132 -- TERESAJ / BOTON BT_ISSUE_OUT
---	DE AQUI SE VA A LA Parte 2 FoliosV2

-- ===================FORMA frmLots  (SECUNDARIA/DEPENDE DE UN PADRE)============================ PARTE #1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 2, 26,	68 -- ARMIDAH /  BOTON BTN_CERRAR_ORDEN /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 3, 26,	145 -- DULCEC /  BOTON BTN_CERRAR_ORDEN /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 4, 26,	64 -- LEONORH / BOTON BTN_CERRAR_ORDEN /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 5, 26,	153 -- ANAC / BOTON BTN_CERRAR_ORDEN /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 6, 26,	154 -- CAROLINAD / BOTON BTN_CERRAR_ORDEN /

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 7, 22,	67 -- GASPARH	/ TextBox3 / 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 8, 22,	68 -- ARMIDAH	/ TextBox3 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 9, 22,	145 -- DULCEC	/ TextBox3 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 10, 22,	64 -- LEONORH	/ TextBox3 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 11, 22,	153 -- ANAC		/ TextBox3 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 12, 22,	154 -- CAROLINAD/ TextBox3 /

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 13, 23,	67 -- GASPARH	/ BOTON Button1 / 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 14, 23,	68 -- ARMIDAH	/ BOTON Button1 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 15, 23,	145 -- DULCEC	/ BOTON Button1 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 16, 23,	64 -- LEONORH	/ BOTON Button1 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 17, 23,	153 -- ANAC		/ BOTON Button1 /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 18, 23,	154 -- CAROLINAD/ BOTON Button1 /

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 19, 26,	144 -- FRANCISCOE / BOTON BTN_CERRAR_ORDEN /

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 20, 20,	144 -- FRANCISCOE / BOTON cmdDetails
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 21, 20,	41 -- RAFAELF / BOTON cmdDetails
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 22, 20,	139 -- ALEJANDROD / BOTON cmdDetails

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 23, 22,	144 -- FRANCISCOE / TextBox3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 24, 23,	144 -- FRANCISCOE / BOTON Button1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 25, 24,	144 -- FRANCISCOE / BOTON cmdCBackout
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 26, 24,	41 -- RAFAELF / BOTON cmdCBackout
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 27, 24,	139 -- ALEJANDROD / BOTON cmdCBackout

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 28, 25,	144 -- FRANCISCOE / BOTON cmdChk
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 29, 25,	41 -- RAFAELF / BOTON cmdChk
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 30, 25,	139 -- ALEJANDROD / BOTON cmdChk

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 31, 25,	87 -- DIANAN / BOTON cmdChk / 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 32, 25,	45 -- PEDROV /  BOTON cmdChk
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 33, 25,	67 -- GASPARH /  BOTON cmdChk / 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 34, 25,	68 -- ARMIDAH /  BOTON cmdChk /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 35, 25,	145 -- DULCEC /  BOTON cmdChk /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 36, 25,	64 -- LEONORH / BOTON cmdChk /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 37, 25,	153 -- ANAC / BOTON cmdChk /
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 38, 25,	154 -- CAROLINAD / BOTON cmdChk /
-- ===============================================DE AQUI VA A LA PARTE#2frmLots

-- ===================FORMA Factuarion============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 39, 30,	41 -- RAFAELF / BOTON Button13

-- ===================FORMA InvD============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 40, 40,	41 -- RAFAELF /  GroupBox3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 41, 40,	59 -- ALEJANDROP / GroupBox3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 42, 40,	77 -- GENAROH /  GroupBox3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 43, 40,	131 -- JESUST /  GroupBox3


-- ===================FORMA eng_main============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 50, 50,	41 -- RAFAELF /  BT_UNLOCK / USUARIO TIPO A1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 51, 50,	89 -- VIVIANAC / BT_UNLOCK
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 52, 50,	139 -- ALEJANDROD / BT_UNLOCK
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 53, 50,	144 -- FRANCISCOE / BT_UNLOCK 

-- ===================FORMA Planning============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 60, 60,	41 -- RAFAELF /  BT_ORDEN_ELIMINAR
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 61, 60,	45 -- PEDROV /  BT_ORDEN_ELIMINAR
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 62, 60,	56 -- MANUELG /  BT_ORDEN_ELIMINAR

-- ===================FORMA HorseDetail============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 63, 72,	98 -- MONICAG /  BT_Processed
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 64, 70,	98 -- MONICAG /  BT_Import
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 65, 71,	98 -- MONICAG /  BT_Transfer2MHI

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 66, 74,	70 -- FERNANDOG /  BTN_IMPORT_MANUAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 67, 74,	41 -- RAFAELF /  BTN_IMPORT_MANUAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 68, 74,	144 -- FEG /  BTN_IMPORT_MANUAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 69, 74,	98 -- MONICAG /  BTN_IMPORT_MANUAL


EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 70, 70,	41 -- RAFAELF /  BT_Import
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 71, 70,	45 -- PEDROV /  BT_Import
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 72, 70,	56 -- MANUELG /  BT_Import

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 73, 71,	41 -- RAFAELF /  BT_Transfer2MHI
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 74, 71,	45 -- PEDROV /  BT_Transfer2MHI
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 75, 71,	56 -- MANUELG /  BT_Transfer2MHI

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 76, 72,	41 -- RAFAELF /  BT_Processed

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 77, 70,	144 -- FRANCISCOE /  BT_Import
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 78, 71,	144 -- FRANCISCOE /  BT_Transfer2MHI
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 79, 73,	144 -- FRANCISCOE /  BT_Transfer2MRD

-- ===================FORMA frmHides  (SECUNDARIA/DEPENDE DE UN PADRE)============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 80, 80,	41 -- RAFAELF /  cmdSave 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 81, 80,	64 -- LEONORH /  cmdSave / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 82, 80,	67 -- GASPARH /  cmdSave / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 83, 80,	68 -- ARMIDAH /  cmdSave / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 84, 80,	153 -- ANAC /  cmdSave / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 85, 80,	93 -- MARIAR /  cmdSave / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 86, 80,	145 -- DULCEC /  cmdSave / USUARIO TIPO P1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 87, 81,	41 -- RAFAELF /  TextBox3 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 88, 81,	64 -- LEONORH /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 89, 81,	67 -- GASPARH /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 90, 81,	68 -- ARMIDAH /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 91, 81,	153 -- ANAC /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 92, 81,	93 -- MARIAR /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 93, 81,	145 -- DULCEC /  TextBox3 / USUARIO TIPO P1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 94, 82,	41 -- RAFAELF /  Button1 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 95, 82,	64 -- LEONORH /  Button1 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 96, 82,	67 -- GASPARH /  Button1 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 97, 82,	68 -- ARMIDAH /  Button1 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 98, 82,	153 -- ANAC /  Button1 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 99, 82,	93 -- MARIAR /  Button1 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 100, 82, 145 -- DULCEC /  Button1 / USUARIO TIPO P1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 101, 80,	154 -- CAROLINAD /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 102, 81,	154 -- CAROLINAD /  TextBox3 / USUARIO TIPO P1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 103, 82,	154 -- CAROLINAD /   Button1 / USUARIO TIPO P1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 104,  82, 198 -- NALLELYC /  Button1 / USUARIO TIPO P1			AX: 20210707
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 105,  81, 198 -- NALLELYC /  TextBox3 / USUARIO TIPO P1			AX: 20210707
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 106,  80, 198 -- NALLELYC /  cmdSave / USUARIO TIPO P1			AX: 20210707
-- ===================FORMA PatternsDatabase============================
/*
SELECT * FROM USUARIO_PEARL WHERE K_USUARIO_PEARL IN (123,63,88,96,114,41,42,139,144 )
*/
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 110, 90,	41 -- RAFAELF /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 111, 90,	42 -- OMARD /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 112, 90,	63 -- LUISP /  Button1
--EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 113, 90,	88 -- SISTEMAS /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 114, 90,	96 -- SANTOSR /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 115, 90,	114 -- JOSUEC /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 116, 90,	123 -- JORGEN /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 117, 90,	139 -- ALEJANDROD /  Button1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 118, 90,	144 -- FRANCISCOE /  Button1

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 119, 91,	41 -- RAFAELF /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 120, 91,	42 -- OMARD /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 121, 91,	63 -- LUISP /  Button2
--EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 122, 91,	88 -- SISTEMAS /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 123, 91,	96 -- SANTOSR /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 124, 91,	114 -- JOSUEC /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 125, 91,	123 -- JORGEN /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 126, 91,	139 -- ALEJANDROD /  Button2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 127, 91,	144 -- FRANCISCOE /  Button2

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 128, 92,	41 -- RAFAELF /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 129, 92,	42 -- OMARD /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 130, 92,	63 -- LUISP /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 131, 92,	88 -- SISTEMAS /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 132, 92,	96 -- SANTOSR /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 133, 92,	114 -- JOSUEC /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 134, 92,	123 -- JORGEN /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 135, 92,	139 -- ALEJANDROD /  Button3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 136, 92,	144 -- FRANCISCOE /  Button3

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 137, 93,	41 -- RAFAELF /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 138, 93,	42 -- OMARD /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 139, 93,	63 -- LUISP /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 140, 93,	88 -- SISTEMAS /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 141, 93,	96 -- SANTOSR /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 142, 93,	114 -- JOSUEC /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 143, 93,	123 -- JORGEN /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 144, 93,	139 -- ALEJANDROD /  Button4
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 145, 93,	144 -- FRANCISCOE /  Button4

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 146, 94,	41 -- RAFAELF /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 147, 94,	42 -- OMARD /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 148, 94,	63 -- LUISP /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 149, 94,	88 -- SISTEMAS /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 150, 94,	96 -- SANTOSR /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 151, 94,	114 -- JOSUEC /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 152, 94,	123 -- JORGEN /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 153, 94,	139 -- ALEJANDROD /  Button6
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 154, 94,	144 -- FRANCISCOE /  Button6

-- ===================FORMA Transferencias============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 170, 100,	41 -- RAFAELF /  ComboBox1 / USUARIO TIPO A1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 171, 100,	42 -- OMARD /  ComboBox1 / USUARIO TIPO Q1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 172, 100,	45 -- PEDROV / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 173, 100,	47 -- MIGUELC / ComboBox1 / USUARIO TIPO Q1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 174, 100,	54 -- GILBERTOV / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 175, 100,	56 -- MANUELG / ComboBox1 / USUARIO TIPO U2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 176, 100,	63 -- LUISP / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 177, 100,	70 -- FERNANDOG / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 178, 100,	72 -- DIANAN / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 179, 100,	87 -- VIVIANAC / ComboBox1 / USUARIO TIPO Q1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 180, 100,	89 -- ERNESTOG / ComboBox1 / USUARIO TIPO U2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 181, 100,	113-- JOSUEC / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 182, 100,	114-- RODOLFOC / ComboBox1 / USUARIO TIPO U1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 183, 100,	132-- TERESAJ / ComboBox1 / USUARIO TIPO U
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 184, 100,	144 -- FEG /  ComboBox1 / USUARIO TIPO A1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 185, 100,	159 -- KARLAR / ComboBox1 / USUARIO TIPO U1			--AX: 20210127
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 186, 100,	162 -- MARLENNES / ComboBox1 / USUARIO TIPO U1		--AX: 20210206
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 187, 100,	139 -- AX / ComboBox1 / USUARIO TIPO U1				--AX: 20210212
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 188, 100,	98 -- MONICAG / ComboBox1 / USUARIO TIPO U1				--AX: 20210212

-- ===================FORMA FO_PO_PREVIEW============================ PARTE#1
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 200, 110,	139	-- AX			/ BT_PRINT_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 201, 110,	57	-- FABIOLA		/ BT_PRINT_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 202, 111,	139	-- AX			/ PANEL MENU
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 203, 111,	57	-- FABIOLA		/ PANEL MENU
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 204, 112,	139	-- AX			/ CHECK POR AUSCENCIA
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 205, 112,	60	-- LIC. ADRIANA	/ CHECK POR AUSCENCIA
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 206, 113,	139	-- AX			/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 207, 113,	57	-- FABIOLA		/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 208, 114,	139	-- AX			/ CONFIRMAR ITEM RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 209, 114,	57	-- FABIOLA		/ CONFIRMAR ITEM RECIBIDO

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 210, 115,	139	-- AX			/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 211, 115,	57	-- FABIOLA		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 212, 116,	139	-- AX			/ CB_LI_FILTRO_ORDENES_COMPLETAS
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 213, 116,	57	-- FABIOLA		/ CB_LI_FILTRO_ORDENES_COMPLETAS
--------------------------------------------- DE AQUI SE VA A LA PARTE#2

-- ===================FORMA FO_PURCHASE_ORDER============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 214, 120,	139	-- AX			/ CHECK BLANKET PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 215, 120,	89	-- VIVIANA		/ CHECK BLANKET PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 216, 120,	87	-- DIANAN		/ CHECK BLANKET PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 217, 120,	159	-- CARLAR		/ CHECK BLANKET PO		--	AX:20210126
--------------------------------------------- --------------------------------------------- --------------------------------------------- 
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 218, 121,	139	-- AX			/ CHECK EDIT_PO_DEPTS	--	AX:20210204
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 219, 121,	57	-- FABIOLA		/ CHECK EDIT_PO_DEPTS	--	AX:20210204
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 220, 121,	60	-- LIC. ADRIANA	/ CHECK EDIT_PO_DEPTS	--	AX:20210204
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 221, 121,	69	-- MARIAS		/ CHECK EDIT_PO_DEPTS	--	AX:20210204
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 222, 121,	157	-- BERENICES	/ CHECK EDIT_PO_DEPTS	--	AX:20210204
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 223, 121,	161	-- ANAM			/ CHECK EDIT_PO_DEPTS	--	AX:20210204

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 224, 120,	131	-- CARLAR		/ CHECK BLANKET PO		--	AX:20210304

-- ===================FORMA FO_PO_PREVIEW============================PARTE#2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 230, 117,	139	-- AX			/ TB_TAX_RATE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 231, 117,	57	-- FABIOLA		/ TB_TAX_RATE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 232, 118,	139	-- AX			/ VER_REPORTE_PRODUCTIVO
--EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 233, 118,	57	-- FABIOLA		/ VER_REPORTE_PRODUCTIVO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 233, 115,	41	-- RAFA			/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 234, 115,	42	-- OMAR			/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 235, 115,	44	-- GUILLERMO	/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 236, 115,	47	-- MIGUELC		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 237, 115,	56	-- MANUELG		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 238, 115,	60	-- ADRIANAD		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 239, 115,	62	-- PATRICIAC	/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 240, 119,	139	-- AX			/ BT_CANCEL_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 241, 119,	57	-- FABIOLA		/ BT_CANCEL_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 242, 131,	139	-- AX			/ BT_PO_PAYMENT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 243, 131,	57	-- FABIOLA		/ BT_PO_PAYMENT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 244, 131,	60	-- LIC. ADRIANA / BT_PO_PAYMENT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 245, 131,	69	-- MARIAS		/ BT_PO_PAYMENT
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 246, 131,	157	-- BERENICES	/ BT_PO_PAYMENT

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 247, 115,	69	-- MARIAS		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 248, 115,	157	-- BERENICES	/ BT_VER_REPORTE

--	SELECT * FROM SISTEMA_CONTROL_PERMISO	WHERE K_SISTEMA_CONTROL_PERMISO	IN (249,250,251,252,253,254,255,256,257,258,259,260)

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 250, 110,	161	-- ANAM		/ BT_PRINT_PO									
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 251, 111,	161	-- ANAM		/ PANEL MENU
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 252, 113,	161	-- ANAM		/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 253, 114,	161	-- ANAM		/ CONFIRMAR ITEM RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 254, 115,	161	-- ANAM		/ BT_VER_REPORTE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 255, 116,	161	-- ANAM		/ CB_LI_FILTRO_ORDENES_COMPLETAS
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 256, 117,	161	-- ANAM		/ TB_TAX_RATE
--EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 257, 118,	161	-- ANAM		/ VER_REPORTE_PRODUCTIVO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 258, 119,	161	-- ANAM		/ BT_CANCEL_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 259, 131,	161	-- ANAM		/ BT_PO_PAYMENT
-------------------------------------------- DE AQUI SE VA A LA PARTE#3


-- ==================FORMA FO_AUTORIZAR_INSPECCION_MATERIAL============================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 300, 150,	41	-- RAFA		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 301, 151,	41	-- RAFA		/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 302, 150,	144	-- FEG		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 303, 151,	144	-- FEG		/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 304, 150,	139	-- AX		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 305, 151,	139	-- AX		/ BTN_GUARDAR_INSPECCION

-- ===============USUARIOS CON PERMISOS PARA AUTORIZAR CAMBIOS EN INSPECCION================================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 306, 150,	47	-- MIGUELC	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 307, 151,	47	-- MIGUELC	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 308, 150,	129	-- MARIOS	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 309, 151,	129	-- MARIOS	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 310, 150,	140	-- JORGEJ	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 311, 151,	140	-- JORGEJ	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 312, 150,	86	-- JORGEO	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 313, 151,	86	-- JORGEO	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 314, 150,	132	-- TERESAJ	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 315, 151,	132	-- TERESAJ	/ BTN_GUARDAR_INSPECCION

-- ===============USUARIOS CON PERMISOS PARA VER INSPECCION================================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 316, 150,	141	-- GEOVANNIL	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 317, 151,	141	-- GEOVANNIL	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 318, 150,	148	-- MIGUELR	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 319, 151,	148	-- MIGUELR	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 320, 150,	162	-- MARLENNES	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 321, 151,	162	-- MARLENNES	/ BTN_GUARDAR_INSPECCION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 322, 150,	142	-- ALBAJ	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 323, 151,	142	-- ALBAJ	/ BTN_GUARDAR_INSPECCION

-- ==================FORMA FO_AUTORIZAR_INSPECCION_PIEL============================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 335, 160,	41	-- RAFA		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 336, 160,	144	-- FEG		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 337, 160,	139	-- AX		/ BT_EDIT	


EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 338, 160,	129	-- MARIOS		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 339, 160,	140	-- JORGEJ		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 340, 160,	86	-- JORGEO		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 341, 160,	162	-- MARLENNES	/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 342, 160,	142	-- ALBAJ		/ BT_EDIT

-- ===================FORMA FO_PO_PREVIEW============================ PARTE#3
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 350, 110,	69	-- MARYS			/ BT_PRINT_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 351, 110,	157	-- BERENICES		/ BT_PRINT_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 352, 111,	69	-- MARYS			/ PANEL MENU
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 353, 111,	157	-- BERENICES		/ PANEL MENU
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 354, 113,	69	-- MARYS			/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 355, 113,	157	-- BERENICES		/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 356, 114,	69	-- MARYS			/ CONFIRMAR ITEM RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 357, 114,	157	-- BERENICES		/ CONFIRMAR ITEM RECIBIDO

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 360, 116,	69	-- MARYS			/ CB_LI_FILTRO_ORDENES_COMPLETAS
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 361, 116,	157	-- BERENICES		/ CB_LI_FILTRO_ORDENES_COMPLETAS

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 362, 117,	69	-- MARYS			/ TB_TAX_RATE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 363, 117,	57	-- BERENICES		/ TB_TAX_RATE
													
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 370, 119,	69	-- MARYS			/ BT_CANCEL_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 371, 119,	57	-- BERENICES		/ BT_CANCEL_PO

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 372, 140,	139	-- AX				/ CRV_PO.ShowPrintButton

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 373, 110,	60	-- LIC. ADRIANA		/ BT_PRINT_PO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 374, 113,	60	-- LIC. ADRIANA		/ CONFIRMAR FECHA RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 375, 114,	60	-- LIC. ADRIANA		/ CONFIRMAR ITEM RECIBIDO
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 376, 116,	60	-- LIC. ADRIANA		/ CB_LI_FILTRO_ORDENES_COMPLETAS
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 377, 117,	60	-- LIC. ADRIANA		/ TB_TAX_RATE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 378, 119,	60	-- LIC. ADRIANA		/ BT_CANCEL_PO

-- ===================FORMA FO_PACKING ADMINISTRACION DE INVENTARIO_EMBARQUE ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 400, 170,	41	-- RAFA		/ BTN_REIMPRIMIR_PACKING_INVOICE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 401, 170,	144	-- FEG		/ BTN_REIMPRIMIR_PACKING_INVOICE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 402, 170,	139	-- AX		/ BTN_REIMPRIMIR_PACKING_INVOICE

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 403, 171,	41	-- RAFA		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 404, 171,	144	-- FEG		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 405, 171,	139	-- AX		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 406, 171,	77	-- GENARO		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 407, 171,	87	-- DIANAN		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 408, 171,	159	-- KARLAR		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 409, 171,	131	-- JESUS		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 410, 172,	41	-- RAFA			/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 411, 172,	144	-- FEG			/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 412, 172,	139	-- AX			/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 413, 172,	77	-- GENARO		/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 414, 172,	87	-- DIANAN		/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 415, 172,	159	-- KARLAR		/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 416, 172,	131	-- JESUS		/ TACCONTROL DE PACKING/INVOICE.

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 417, 171,	45	-- PEDROV		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 418, 172,	45	-- PEDROV		/ TACCONTROL DE PACKING/INVOICE.

-- use BD_GENERAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 419, 172,	98	-- MONICAG		/ TACCONTROL DE PACKING/INVOICE.
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 420, 171,	98	-- MONICAG		/ BOTON PARA REGRESAR MATERIAL A INVENTARIO.

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 421, 172,	182	-- JOSER		/ TACCONTROL DE PACKING/INVOICE.

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 422, 170,	87	-- DIANAN		/ BTN_REIMPRIMIR_PACKING_INVOICE
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 423, 173,	87	-- DIANAN		/  BTN_VER_ORDEN_FACTURACION

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 424, 173,	144	-- FEG		/  BTN_VER_ORDEN_FACTURACION
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 425, 174,	144	-- FEG		/  BTN_ADMINISTRAR_FACTURA

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 426, 174,	87	-- DIANAN		/  BTN_ADMINISTRAR_FACTURA

-- ===============================================

-- ===================FORMA FoliosV2============================ Parte 2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 450, 1,	162 -- MARLENNES / BOTON BT_ISSUE_OUT	--AX: 20210206
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 451, 1,	144 -- FRANCISCOE / BOTON BT_ISSUE_OUT

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 452, 2,	144 -- FRANCISCOE / GROUP BOX GB_QC_DETALLADO

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 453, 1,	41 -- RAFA / BOTON BT_ISSUE_OUT

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 454, 2,	162 -- FRANCISCOE / GROUP BOX GB_QC_DETALLADO

-- ===================			FORMA SupMat		========================	(59,120,160,172,136,87,58,165,70,131,75,159,164,56,98,169,45,90, 41,139,144)	AX: 20210306
-- ===================			PARA LOS USUARIOS DE MATERIALES.
---												 IDENTI - IDFOR -#USER
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 470, 180,	45	-- PEDROV		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 471, 180,	56	-- MANUEL		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 472, 180,	58	-- DIANAS		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 473, 180,	59	-- ALEJANDROP	/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 474, 180,	70	-- FERNANDOG	/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 475, 180,	75	-- KARENA		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 476, 180,	87	-- DIANAN		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 477, 180,	90	-- TANIAC		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 478, 180,	98	-- MONICAG		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 479, 180,	120	-- ALFREDOA		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 480, 180,	131	-- JESUST		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 481, 180,	136	-- CRISTALV		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 482, 180,	159	-- KARLAR		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 483, 180,	160	-- ALONDRAH		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 484, 180,	164	-- LUISE		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 485, 180,	165	-- EVAR			/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 486, 180,	169	-- OLGAM		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 487, 180,	172	-- ANGELAE		/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 488, 180,	41	-- RAFA			/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 489, 180,	144	-- FEG			/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 490, 180,	139	-- AX			/ DG_LISTING_ORDENES_PENDIENTES
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 491, 180,	175	-- ANGELICAS	/ DG_LISTING_ORDENES_PENDIENTES		AX:20210324
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 492, 180,	183	-- HEIDYM		/ DG_LISTING_ORDENES_PENDIENTES		FEG:20210415
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 493, 180,	180	-- CINTHIAV		/ DG_LISTING_ORDENES_PENDIENTES		AX:20210506		
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 494, 180,	181	-- ANAG			/ DG_LISTING_ORDENES_PENDIENTES		AX:20210506		

-- use BD_GENERAL
-- ===================FORMA HorseDetail============================ Parte 2
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 550, 74,	139 -- ALEX /  BTN_IMPORT_MANUAL
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 551, 74,	120 -- ALFREDOA /  BTN_IMPORT_MANUAL 

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 552, 71,	90 -- TANIAC /  BT_Transfer2MHI
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 553, 74,	90 -- TANIAC /  BTN_IMPORT_MANUAL

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 554, 72,	87 -- DIANAN /  BT_Processed
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 555, 70,	87 -- DIANAN /  BT_Import
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 556, 71,	87 -- DIANAN /  BT_Transfer2MHI
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 557, 74,	87 -- DIANAN /  BTN_IMPORT_MANUAL


-- ===================FORMA frmLots  (SECUNDARIA/DEPENDE DE UN PADRE)============================ PARTE#2frmLots
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 600, 26,	187 -- ELENAP	/ BOTON BTN_CERRAR_ORDEN /		AX:20210519
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 601, 22,	187 -- ELENAP	/ TextBox3 /					AX:20210519
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 602, 23,	187 -- ELENAP	/ BOTON Button1 /				AX:20210519
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 603, 25,	187 -- ELENAP	/ BOTON cmdChk /				AX:20210519

EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 604, 26,	198 -- NALLELYC /  BOTON BTN_CERRAR_ORDEN /		AX:20210707
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 605, 22,	198 -- NALLELYC	/ TextBox3 /					AX:20210707
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 606, 23,	198 -- NALLELYC	/ BOTON Button1 /				AX:20210707
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 607, 25,	198 -- NALLELYC	/ BOTON cmdChk /				AX:20210707


-- ===================FORMA PLANNING ========================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 800, 200,	144	-- FEG		/ BT_EDIT /BOTON PARA EDITAR ORDEN

SET NOCOUNT OFF
GO
-- ===============================================

--IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_SISTEMA_CONTROL_PERMISO]') AND type in (N'P', N'PC'))
--	DROP PROCEDURE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO]
--GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
