-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	RH
-- // MODULO:			
-- // OPERACION:		GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	04/FEB/2020
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[GRUPO_APROBADOR]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTATUS_GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[ESTATUS_GRUPO_APROBADOR]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[TIPO_GRUPO_APROBADOR]
GO


-- //////////////////////////////////////////////////////////////
-- // TIPO_GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[TIPO_GRUPO_APROBADOR] (
	[K_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[D_TIPO_GRUPO_APROBADOR]	[VARCHAR] (100) NOT NULL,
	[S_TIPO_GRUPO_APROBADOR]	[VARCHAR] (20)	NOT NULL,
	[O_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[C_TIPO_GRUPO_APROBADOR]	[VARCHAR] (255) NOT NULL,
	[L_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[TIPO_GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_TIPO_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_TIPO_GRUPO_APROBADOR])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_TIPO_GRUPO_APROBADOR_01_DESCRIPCION] 
	   ON [dbo].[TIPO_GRUPO_APROBADOR] ( [D_TIPO_GRUPO_APROBADOR] )
GO
-- //////////////////////////////////////////////////////////////
--ALTER TABLE [dbo].[TIPO_GRUPO_APROBADOR] ADD 
--	CONSTRAINT [FK_TIPO_GRUPO_APROBADOR_01] 
--		FOREIGN KEY ( [L_TIPO_GRUPO_APROBADOR] ) 
--		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
--GO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_TIPO_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR]
GO
CREATE PROCEDURE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_TIPO_GRUPO_APROBADOR	INT,
	@PP_D_TIPO_GRUPO_APROBADOR	VARCHAR(100),
	@PP_S_TIPO_GRUPO_APROBADOR	VARCHAR(20),
	@PP_O_TIPO_GRUPO_APROBADOR	INT,
	@PP_C_TIPO_GRUPO_APROBADOR	VARCHAR(255),
	@PP_L_TIPO_GRUPO_APROBADOR	INT
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT
	SELECT	@VP_K_EXISTE =	K_TIPO_GRUPO_APROBADOR
							FROM	TIPO_GRUPO_APROBADOR
							WHERE	K_TIPO_GRUPO_APROBADOR=@PP_K_TIPO_GRUPO_APROBADOR
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO TIPO_GRUPO_APROBADOR	
			(	K_TIPO_GRUPO_APROBADOR,				D_TIPO_GRUPO_APROBADOR, 
				S_TIPO_GRUPO_APROBADOR,				O_TIPO_GRUPO_APROBADOR,
				C_TIPO_GRUPO_APROBADOR,
				L_TIPO_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_TIPO_GRUPO_APROBADOR,			@PP_D_TIPO_GRUPO_APROBADOR,	
				@PP_S_TIPO_GRUPO_APROBADOR,			@PP_O_TIPO_GRUPO_APROBADOR,
				@PP_C_TIPO_GRUPO_APROBADOR,
				@PP_L_TIPO_GRUPO_APROBADOR			)
	ELSE
		UPDATE	TIPO_GRUPO_APROBADOR
		SET		D_TIPO_GRUPO_APROBADOR	= @PP_D_TIPO_GRUPO_APROBADOR,	
				S_TIPO_GRUPO_APROBADOR	= @PP_S_TIPO_GRUPO_APROBADOR,			
				O_TIPO_GRUPO_APROBADOR	= @PP_O_TIPO_GRUPO_APROBADOR,
				C_TIPO_GRUPO_APROBADOR	= @PP_C_TIPO_GRUPO_APROBADOR,
				L_TIPO_GRUPO_APROBADOR	= @PP_L_TIPO_GRUPO_APROBADOR	
		WHERE	K_TIPO_GRUPO_APROBADOR=@PP_K_TIPO_GRUPO_APROBADOR
	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////
-- ===============================================
SET NOCOUNT ON
-- ===============================================

--=========PARA DESCRIPCION DE PUESTOS========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 1, 'CREAR DESCRIPCION PUESTO',		'CREA_DP', 1, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 2, 'AUTORIZAR DESCRIPCION PUESTO',	'AUTOR_DP', 2, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 3, 'NOTIFICAR DESCRIPCION PUESTO',	'NOTIF_DP', 3, '', 1

--=========PARA MQU SALIDA PANTALLA FOLIOS CONTROLADOS========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 21, 'MQU SALIDA',					'MQU_SAL', 21, '', 1

--=========PARA MSL SALIDA PANTALLA FOLIOS CONTROLADOS=======================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 23, 'MSL SALIDA',					'MSL_SAL', 23, '', 1

--=========PARA MHI SALIDA PANTALLA FOLIOS CONTROLADOS=======================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 25, 'MHI SALIDA',					'MHI_SAL', 25, '', 1

--=========PARA MRD SALIDA PANTALLA FOLIOS CONTROLADOS========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 30, 'MRD SALIDA',					'MRD_SAL', 30, '', 1

--=========PARA MFP ENTRADA PANTALLA FOLIOS TX7========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 41, 'MFP NOTIFICAR ENTRADA',		'MFP_NOT_ENT', 41, '', 1

--=========PARA MHI ENTRADA PANTALLA FOLIOS TX7========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 51, 'MHI NOTIFICAR ENTRADA',		'MHI_NOT_ENT', 51, '', 1

--=========PARA TRANSFERIR ORDEN COMPLETADA PANTALLA Transferencias========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 61, 'TRANSFERIR ORDEN COMPLETA',	'TRA_ORD_C',	61, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 62, 'TRANSFERIR ORDEN TX7',		'TRA_ORD_TX7',	62, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 63, 'LOTE NO COMPATIBLE',			'LOT_NO_COMP',	63, '', 1

--=========PARA TRANSFERIR ORDEN COMPLETADA PANTALLA IncInsp========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 81, 'MODIFICAR ESTATUS REPORTE',	'MOD_EST_RPT',	81, '', 1

--=========PARA SELECCIONAR TODOS LOS KITS PANTALLA frmKits========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 101, 'SELECCIONAR TODO',			'SELEC_TODO',	101, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 102, 'ABRIR ORDEN',				'ABR_ORD',		102, '', 1

--=========PARA CERRAR ORDEN PANTALLA FORMLOTS========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 121, 'CERRAR ORDEN',				'CERR_ORD', 121, '', 1

--=========GRUPO PARA AUTORIZAR CAMBIOS EN INSPECCION  DE MATERIAL PANTALLA AUTORIZAR INSPECCION MATERIAL========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 150, 'MODIFICAR INSPECCION MATERIAL QA',	'MOD_INS_QA', 150, '', 1

--=========GRUPO PARA NOTIFICAR QUE EL MATERIAL HA SIDO LIBERADO/RECHAZADO PARA DISPOSICION PANTALLA AUTORIZAR INSPECCION MATERIAL========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 180, 'NOTIFICAR MHI MATERIAL LIBERADO POR QA',	'MHI_LIB', 180, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 200, 'NOTIFICAR MQU MATERIAL RECHAZADO POR QA', 'MQU_REC', 200, '', 1

--=========GRUPO AUTORIZADO PARA ENVIAR MATERIAL DE INVENTARIO A CALIDAD/QC========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 300, 'ENVIAR_MATERIAL_A_QC',						'ENV_MAT_QC', 300, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 350, 'ENVIAR_MATERIAL_A_INVENTARIO',				'ENV_MAT_IN', 350, '', 1

-- USE BD_GENERAL
--=========PARA UATORIZAR MODIFICACION Y ELIMINACION DE ORDEN PANTALLA FO_PLANNING========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 400, 'MODIFICAR/ELIMANAR ORDEN',					'UP_DL_ORD', 400, '', 1


-- USE BD_GENERAL
--=========PARA LEER TICKES DE PIELES DE ORDEN PANTALLA IMPOR HIDE========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 450, 'LEER TICKET',					'LEE_TICKET', 450, '', 1

-- USE BD_GENERAL
--=========MARCAR PIEL PARA DEVOLUCION EN MESA========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 500, 'MARCAR PIEL PARA DEVOLUCION',					'DEVOL_MESA', 500, '', 1

-- USE BD_GENERAL
--=========PARA TRASPASAR PIEL ENTRE ORDENES EN PRD========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 550, 'TRASPASAR PIEL A ORDEN',					'TRSPSO_PRD', 550, '', 1

-- =============================================== USE BD_GENERAL===============================================
-- ================================= GRUPOS APROBADORES PARA PO	================================== AX
-- =============================================== -- ===============================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6001, 'CREAR PO',					'CREAR_PO',	6001, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6002, 'AUTORIZAR PO',				'AUTOR_PO', 6002, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6003, 'NOTIFICAR PO',				'NOTIF_PO', 6003, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6004, 'IMPRIMIR PO',				'IMPRI_PO', 6004, '', 1
-- =============================================== USE BD_GENERAL===============================================
-- ================================= NOTIFICACIONES DE PEDIDO Y RECIBOS	================================== AX
-- =============================================== -- ===============================================	
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 7800, 'MATERIAL SIN PARAMETROS INSPECCIÓN',		'INSPEC_BPO',	7800, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 7801, 'REQUISICIÓN DE MATERIAL DE BLANKET_PO',		'REQUIS_BPO',	7801, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 7900, 'MATERIAL RECIBIDO PARA INSPECCIONAR',		'RECIBI_BPO',	7900, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 7901, 'MATERIAL RECIBIDO CON EXCEDENTE',			'RECEXC_BPO',	7901, '', 1

-- ================================= NOTIFICACIONES COMPATIBILIDAD DE LOTES	================================== AX
-- =============================================== -- ===============================================	
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 9200, 'USUARIO PARA NOTIFICACION DE LOTES COMPATIBLES',		'LOT_COMPAT',	9200, '', 1		-- AX: 20210301

-- ================================= NOTIFICACIONES INVENTARIO MATERIAL CONTROLADO	================================== AX
-- ================================= CUANDO EL STOCK DE MATERIAL(PRODUCCIÓN) SE ENCUENTRA EN CANTIDADES MÍNIMAS.
-- =============================================== -- ===============================================	
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 9600, 'NOTIFICACION CANTIDADES MÍNIMAS EN STOCK HILO',			'STOCK_MIN_HILO',	9600, '', 1		-- AX: 20210519
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 8300, 'NOTIFICACION CANTIDADES MÍNIMAS EN STOCK MULLER',		'STOCK_MIN_MULL',	8300, '', 1		-- AX: 20210519

-- ================================= NOTIFICACIONES RMA Y PES	================================== AX
-- ================================= CUANDO SE GENERA UNA ORDEN POR RECHAZO O POR UN PEDIDO ESPECIAL DE PARTE DEL CLIENTE.
-- =============================================== -- ===============================================	
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 9702, 'AUTORIZAR RMA/PES',									'AUTORIZAR RMA/PES',	9702, '', 1		-- AX: 20210519
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 9703, 'NOTIFICAR RMA/PES',									'NOTIFICAR RMA/PES',	9703, '', 1		-- AX: 20210519
GO


-- ===============================================
SET NOCOUNT OFF
-- ===============================================



-- //////////////////////////////////////////////////////////////
-- // ESTATUS_GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////


CREATE TABLE [dbo].[ESTATUS_GRUPO_APROBADOR] (
	[K_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[D_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (100) NOT NULL,
	[S_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (10)	NOT NULL,
	[O_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[C_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (255) NOT NULL,
	[L_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_ESTATUS_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_ESTATUS_GRUPO_APROBADOR])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ESTATUS_GRUPO_APROBADOR_01_DESCRIPCION] 
	   ON [dbo].[ESTATUS_GRUPO_APROBADOR] ( [D_ESTATUS_GRUPO_APROBADOR] )
GO

-- //////////////////////////////////////////////////////////////


--ALTER TABLE [dbo].[ESTATUS_GRUPO_APROBADOR] ADD 
--	CONSTRAINT [FK_ESTATUS_GRUPO_APROBADOR_01] 
--		FOREIGN KEY ( [L_ESTATUS_GRUPO_APROBADOR] ) 
--		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
--GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]
GO


CREATE PROCEDURE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_ESTATUS_GRUPO_APROBADOR	INT,
	@PP_D_ESTATUS_GRUPO_APROBADOR	VARCHAR(100),
	@PP_S_ESTATUS_GRUPO_APROBADOR	VARCHAR(10),
	@PP_O_ESTATUS_GRUPO_APROBADOR	INT,
	@PP_C_ESTATUS_GRUPO_APROBADOR	VARCHAR(255),
	@PP_L_ESTATUS_GRUPO_APROBADOR	INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_ESTATUS_GRUPO_APROBADOR
							FROM	ESTATUS_GRUPO_APROBADOR
							WHERE	K_ESTATUS_GRUPO_APROBADOR=@PP_K_ESTATUS_GRUPO_APROBADOR

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO ESTATUS_GRUPO_APROBADOR	
			(	K_ESTATUS_GRUPO_APROBADOR,				D_ESTATUS_GRUPO_APROBADOR, 
				S_ESTATUS_GRUPO_APROBADOR,				O_ESTATUS_GRUPO_APROBADOR,
				C_ESTATUS_GRUPO_APROBADOR,
				L_ESTATUS_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_ESTATUS_GRUPO_APROBADOR,			@PP_D_ESTATUS_GRUPO_APROBADOR,	
				@PP_S_ESTATUS_GRUPO_APROBADOR,			@PP_O_ESTATUS_GRUPO_APROBADOR,
				@PP_C_ESTATUS_GRUPO_APROBADOR,
				@PP_L_ESTATUS_GRUPO_APROBADOR			)
	ELSE
		UPDATE	ESTATUS_GRUPO_APROBADOR
		SET		D_ESTATUS_GRUPO_APROBADOR	= @PP_D_ESTATUS_GRUPO_APROBADOR,	
				S_ESTATUS_GRUPO_APROBADOR	= @PP_S_ESTATUS_GRUPO_APROBADOR,			
				O_ESTATUS_GRUPO_APROBADOR	= @PP_O_ESTATUS_GRUPO_APROBADOR,
				C_ESTATUS_GRUPO_APROBADOR	= @PP_C_ESTATUS_GRUPO_APROBADOR,
				L_ESTATUS_GRUPO_APROBADOR	= @PP_L_ESTATUS_GRUPO_APROBADOR	
		WHERE	K_ESTATUS_GRUPO_APROBADOR=@PP_K_ESTATUS_GRUPO_APROBADOR

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////




-- ===============================================
SET NOCOUNT ON
-- ===============================================

EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 0, 'INACTIVO',			'INACTVO', 0, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 1, 'ACTIVO',			'ACTIVO', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 2, 'SUSPENDIDO',		'SUSPNDO', 2, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 3, 'APROBADO',		'APROB', 3, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 4, 'CANCELADO',		'CANCEL', 4, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 4, 'VENCIDO',			'CANCEL', 4, '', 1

GO


-- ===============================================
SET NOCOUNT OFF
-- ===============================================




-- //////////////////////////////////////////////////////////////
-- // GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[GRUPO_APROBADOR] (
	[K_GRUPO_APROBADOR]				[INT]			NOT NULL,
	-- =================================	
	[D_GRUPO_APROBADOR]				VARCHAR(100)	NOT NULL,	
	[S_GRUPO_APROBADOR]				VARCHAR(50)		NOT NULL,
	-- =================================
	[K_USUARIO]						[INT]			NOT NULL,
	[K_TIPO_GRUPO_APROBADOR]		[INT]			NOT NULL,	
	[K_ESTATUS_GRUPO_APROBADOR]		[INT]			NOT NULL,
	-- =================================	
)ON [PRIMARY]	
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_GRUPO_APROBADOR])
GO

-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[GRUPO_APROBADOR] ADD 
	CONSTRAINT [FK_GRUPO_APROBADOR_01]  
		FOREIGN KEY ([K_ESTATUS_GRUPO_APROBADOR]) 
		REFERENCES [dbo].[ESTATUS_GRUPO_APROBADOR] ([K_ESTATUS_GRUPO_APROBADOR]),
	CONSTRAINT [FK_GRUPO_APROBADOR_02]  
		FOREIGN KEY ([K_TIPO_GRUPO_APROBADOR]) 
		REFERENCES [dbo].[TIPO_GRUPO_APROBADOR] ([K_TIPO_GRUPO_APROBADOR])
	--CONSTRAINT [FK_GRUPO_APROBADOR_03]  
	--	FOREIGN KEY ([K_USUARIO]) 
	--	REFERENCES DATA_02.[dbo].[users_pearl] ([codigo])
GO


-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_GRUPO_APROBADOR]
GO


CREATE PROCEDURE [dbo].[PG_CI_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_GRUPO_APROBADOR		INT,
	@PP_D_GRUPO_APROBADOR		VARCHAR(100),
	@PP_S_GRUPO_APROBADOR		VARCHAR(10),
	@PP_K_USUARIO				INT,
	@PP_K_TIPO_GRUPO_APROBADOR	INT,
	@PP_K_ESTATUS_APROBADOR		INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_GRUPO_APROBADOR
							FROM	GRUPO_APROBADOR
							WHERE	K_GRUPO_APROBADOR=@PP_K_GRUPO_APROBADOR

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO GRUPO_APROBADOR	
			(	K_GRUPO_APROBADOR,				D_GRUPO_APROBADOR, 
				S_GRUPO_APROBADOR,				K_USUARIO,
				K_TIPO_GRUPO_APROBADOR,
				K_ESTATUS_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_GRUPO_APROBADOR,			@PP_D_GRUPO_APROBADOR,	
				@PP_S_GRUPO_APROBADOR,			@PP_K_USUARIO,
				@PP_K_TIPO_GRUPO_APROBADOR,
				@PP_K_ESTATUS_APROBADOR			)
	ELSE
		UPDATE	GRUPO_APROBADOR
		SET		D_GRUPO_APROBADOR			= @PP_D_GRUPO_APROBADOR,	
				S_GRUPO_APROBADOR			= @PP_S_GRUPO_APROBADOR,			
				K_USUARIO					= @PP_K_USUARIO,
				K_TIPO_GRUPO_APROBADOR		= @PP_K_TIPO_GRUPO_APROBADOR,
				K_ESTATUS_GRUPO_APROBADOR	= @PP_K_ESTATUS_APROBADOR	
		WHERE	K_GRUPO_APROBADOR=@PP_K_GRUPO_APROBADOR

	-- =========================================================
GO



-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- USE BD_GENERAL
-- ===================USUARIOS PARA DESCRIPCION DE PUESTO PARA PRUEBAS / SE HACE CON LOS NUMEORS DE RELOJ============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 13367, 1, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 2, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 7945, 1, 1 -- PATRICIAC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 3, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 8524, 1, 1 -- IRISE

-- ===================USUARIOS PARA DESCRIPCION DE PUESTO GERENTES / SE HACE CON LOS NUMEORS DE RELOJ============================
/*
K_RESPONSABLE_PUESTO
22
52
67
181
1299
4475
7945
*/

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 4, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 22,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 5, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 52,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 6, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 67,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 7, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 181, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 8, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 1299, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 9, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 4475, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 10, 'APROBADORES DESCRIPCION DE PUESTO',	'APROB_DP', 7945, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 11, 'APROBADORES DESCRIPCION DE PUESTO',	'APROB_DP', 6142, 2,1

-- ===================USUARIOS AUTORIZADOS PARA SALIDA DE MQU EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 51, 'AUTORIZAR SALIDA MQU',					'AUT_SL_MQU', 144, 21, 0 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 52, 'AUTORIZAR SALIDA MQU',					'AUT_SL_MQU', 132, 21, 1 --TERESAJ
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 53, 'AUTORIZAR SALIDA MQU',					'AUT_SL_MQU', 162, 21, 1 --MARLENNES	--AX: 20210206

-- ===================USUARIOS AUTORIZADOS PARA SALIDA DE MSL EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 61, 'AUTORIZAR SALIDA MSL',					'AUT_SL_MSL', 144, 23, 0 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 62, 'AUTORIZAR SALIDA MSL',					'AUT_SL_MSL', 173, 23, 1 --PEDROS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 63, 'AUTORIZAR SALIDA MSL',					'AUT_SL_MSL', 47, 23, 1 --MIGUELC	
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 64, 'AUTORIZAR SALIDA MSL',					'AUT_SL_MSL', 41, 23, 0 --RAFAELF	
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 65, 'AUTORIZAR SALIDA MSL',					'AUT_SL_MSL', 139, 23, 0 --AX	


-- ===================USUARIOS AUTORIZADOS PARA SALIDA DE MRD EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 71, 'AUTORIZAR SALIDA MRD',					'AUT_SL_MRD', 144, 30, 0 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 72, 'AUTORIZAR SALIDA MRD',					'AUT_SL_MRD', 89, 30, 1 --VIVIANAC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 73, 'AUTORIZAR SALIDA MRD',					'AUT_SL_MRD', 108, 30, 1 --VICTORC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 74, 'AUTORIZAR SALIDA MRD',					'AUT_SL_MRD', 42, 30, 1 --OMARD
--SELECT  * FROM USUARIO_PEARL

-- ===================USUARIOS AUTORIZADOS PARA SALIDA DE MHI EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 85, 'AUTORIZAR SALIDA MHI',					'AUT_SL_MHI', 144, 25, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 86, 'AUTORIZAR SALIDA MHI',					'AUT_SL_MHI', 45, 25, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 87, 'AUTORIZAR SALIDA MHI',					'AUT_SL_MHI', 56, 25, 1 --MANUELG	

-- ===================ENVIAR CORREO PARA MFP DE ENTRADA DE PIELES EN PANTALLA FOLIOS============================
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 101, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 45, 41, 1 -- PEDROV

--DELETE	GRUPO_APROBADOR	WHERE	K_GRUPO_APROBADOR IN (101)			AX:	20210409 SE ELIMINARON LOS PERMISOS A PEDROV A PETICIÓN DEL USUARIO.

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 102, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 56, 41, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 103, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 70, 41, 1 -- FERNANDOG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 104, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 87, 41, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 105, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 144, 41, 1 -- FEG

-- ===================ENVIAR CORREO PARA MFP DE ENTRADA DE PIELES EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 120, 'NOTIFICAR ENTRADA MHI',				'NOT_EN_MHI', 45, 51, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 121, 'NOTIFICAR ENTRADA MHI',				'NOT_EN_MHI', 87, 51, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 122, 'NOTIFICAR ENTRADA MHI',				'NOT_EN_MHI', 144, 51, 1 -- FEG

-- ===================USUARIOS PARA TRANSFERIR ORDEN COMPLETADA PANTALLA Transferencias============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 151, 'TRANSFERIR ORDEN',					'TRANS_ORD', 41, 61, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 152, 'TRANSFERIR ORDEN',					'TRANS_ORD', 45, 61, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 153, 'TRANSFERIR ORDEN',					'TRANS_ORD', 54, 61, 0 -- GILBERTOV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 154, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 61, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 155, 'TRANSFERIR ORDEN',					'TRANS_ORD', 63, 61, 0 -- LUISP
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 156, 'TRANSFERIR ORDEN',					'TRANS_ORD', 98, 61, 1 -- MONICAG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 157, 'TRANSFERIR ORDEN',					'TRANS_ORD', 72, 61, 0 -- ROXANAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 158, 'TRANSFERIR ORDEN',					'TRANS_ORD', 87, 61, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 159, 'TRANSFERIR ORDEN',					'TRANS_ORD', 113, 61, 0 -- ERNESTOG

-- ===================USUARIOS PARA TRANSFERIR ORDEN TX7 PANTALLA Transferencias============================PARTE #1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 160, 'TRANSFERIR ORDEN',					'TRANS_ORD', 144, 62, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 161, 'TRANSFERIR ORDEN',					'TRANS_ORD', 45, 62, 0 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 162, 'TRANSFERIR ORDEN',					'TRANS_ORD', 41, 62, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 163, 'TRANSFERIR ORDEN',					'TRANS_ORD', 87, 62, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 164, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 62, 1 -- MANUELG
------------ DE AQUI SE VA A LA PARTE #2

-- ===================USUARIOS PARA TRANSFERIR LOTES NO COMPATIBLES PANTALLA Transferencias============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 165, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 63, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 166, 'TRANSFERIR ORDEN',					'TRANS_ORD', 92, 63, 1 -- JOSES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 167, 'TRANSFERIR ORDEN',					'TRANS_ORD', 48, 63, 1 -- IVAND
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 168, 'TRANSFERIR ORDEN',					'TRANS_ORD', 47, 63, 1 -- MIGUELC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 169, 'TRANSFERIR ORDEN',					'TRANS_ORD', 86, 63, 1 -- JORGEO


-- ===================USUARIOS PARA TRANSFERIR ORDEN TX7 PANTALLA Transferencias============================PARTE #2
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 170, 'TRANSFERIR ORDEN',					'TRANS_ORD', 98, 62, 0 -- MONICAG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 171, 'TRANSFERIR ORDEN',					'TRANS_ORD', 139, 62, 1 -- AX


-- ===================USUARIOS PARA MODIFICAR ESTATUS DEL REPORTE PANTALLA IncInsp============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 200, 'REPORTE INCOMING INSPECTION',			'RPT_INC_IN', 47, 81, 1 -- MIGUELC

-- ===================USUARIOS PARA ABRIR LA ORDEN COMPLETADA PANTALLA frmKits============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 248, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 139, 102, 1 -- AX

-- ===================USUARIOS PARA SELECCIONAR TODOS LOS KITS PANTALLA frmKits============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 249, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 154, 101, 1 -- CAROLINAD
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 250, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 41, 101, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 251, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 68, 101, 1 -- ARMIDAH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 252, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 153, 101, 1 -- ANAC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 253, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 64, 101, 1 -- LEONORH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 254, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 49, 101, 1 -- OSCART
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 255, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 44, 101, 1 -- GUILLERMOM
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 256, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 67, 101, 1 -- GASPARH

-- ===================USUARIOS PARA ABRIR LA ORDEN COMPLETADA PANTALLA frmKits============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 257, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 41, 102, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 258, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 44, 102, 1 -- GUILLERMOM
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 259, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 144, 102, 0 -- FEG

-- =============================================== -- ===============================================
-- ================================= GRUPOS APROBADORES PARA PO	================================== AX
-- =============================================== -- ===============================================
-- #6001- 'CREAR PO',		#6002- 'AUTORIZAR PO',		#6003- 'NOTIFICAR PO',		#6004- 'IMPRIMIR PO'
-- =================================			CREAR PO		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 260, 'CREAR PO',			'USR_IN_PO', 62,	6001, 1		-- PATY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 261, 'CREAR PO',			'USR_IN_PO', 115,	6001, 1		-- SONIA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 262, 'CREAR PO',			'USR_IN_PO', 121,	6001, 1		-- LUCY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 263, 'CREAR PO',			'USR_IN_PO', 125,	6001, 1		-- IRIS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 264, 'CREAR PO',			'USR_IN_PO', 145,	6001, 1		-- DULCEC

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 265, 'CREAR PO',			'USR_IN_PO', 41,	6001, 1		-- RAFA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 266, 'CREAR PO',			'USR_IN_PO', 42,	6001, 1		-- OMAR
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 267, 'CREAR PO',			'USR_IN_PO', 139,	6001, 1		-- AX
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 268, 'CREAR PO',			'USR_IN_PO', 144,	6001, 1		-- FEG
-- =================================			DE AQUÍ SE VA A LA SEGUNDA PARTE.
-- =================================	AUTORIZAR PO - GERENTES	  ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 269, 'AUTORIZAR PO',		'USR_UP_PO', 62,	6002, 1		-- PATY			RH / SEG / ENFER
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 270, 'AUTORIZAR PO',		'USR_UP_PO', 42,	6002, 1		-- OMAR			SIST/PROY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 271, 'AUTORIZAR PO',		'USR_UP_PO', 44,	6002, 1		-- GUILLERMO	PROD / MTTO / ING
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 272, 'AUTORIZAR PO',		'USR_UP_PO', 47,	6002, 1		-- MIKE			QC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 273, 'AUTORIZAR PO',		'USR_UP_PO', 56,	6002, 1		-- MANUELG		MATERIALES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 274, 'AUTORIZAR PO',		'USR_UP_PO', 60,	6002, 1		-- ADRIANA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 275, 'AUTORIZAR PO',		'USR_UP_PO', 57,	6002, 1		-- FABIOLA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 276, 'AUTORIZAR PO',		'USR_UP_PO', 139,	6002, 1		-- AX			PRUEBAS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 280, 'AUTORIZAR PO',		'USR_UP_PO', 41,	6002, 1		-- RAFAELF		SISTEMAS		
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 281, 'AUTORIZAR PO',		'USR_UP_PO', 156,	6002, 1		-- OMARG		MANTENIMIENTO

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 282, 'AUTORIZAR PO',		'USR_UP_PO', 69,	6002, 1		-- MARIAS		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 283, 'AUTORIZAR PO',		'USR_UP_PO', 157,	6002, 1		-- BERENICES	FINANZAS

-- =================================			IMPRIMIR PO 	  ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 278, 'IMPRIMIR PO',			'USR_IM_PO', 57,	6004, 1		-- FABIOLA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 279, 'IMPRIMIR PO',			'USR_IM_PO', 139,	6004, 1		-- AX

-- =================================			NOTIFICAR PO 	  ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 284, 'NOTIFICAR PO',		'USR_NOT_PO', 139,	6003, 1		-- AX
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 285, 'NOTIFICAR PO',		'USR_NOT_PO', 57,	6003, 1		-- FABIOLA

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 286, 'NOTIFICAR PO',		'USR_NOT_PO', 62,	6003, 1		-- PATY			RH / SEG / ENFER
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 287, 'NOTIFICAR PO',		'USR_NOT_PO', 42,	6003, 1		-- OMAR			SIST/PROY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 288, 'NOTIFICAR PO',		'USR_NOT_PO', 44,	6003, 1		-- GUILLERMO	PROD / MTTO / ING
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 289, 'NOTIFICAR PO',		'USR_NOT_PO', 47,	6003, 1		-- MIKE			QC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 290, 'NOTIFICAR PO',		'USR_NOT_PO', 56,	6003, 1		-- MANUELG		MATERIALES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 291, 'NOTIFICAR PO',		'USR_NOT_PO', 60,	6003, 1		-- ADRIANA		FINANZAS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 292, 'AUTORIZAR PO',		'USR_UP_PO', 161,	6002, 1		-- ANAM			FINANZAS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 293, 'NOTIFICAR PO',		'USR_NOT_PO', 41,	6003, 1		-- RAFAELF		SISTEMAS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 294, 'CREAR PO',			'USR_IN_PO',  198,	6001, 1		-- NALLELYC			AX: 20210707
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 295, 'NOTIFICAR PO',		'USR_NOT_PO', 198,	6003, 0		-- NALLELYC			AX: 20210707

--=========PARA CERRAR ORDEN PANTALLA FORMLOTS========================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 301, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 144, 121, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 302, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 41, 121, 1 --RAFA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 303, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 44, 121, 1 --GUILLERMO
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 87, 121, 1 --DIANAN

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 305, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 45, 121, 1 --PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 306, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 67, 121, 1 --GASPARH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 307, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 68, 121, 1 --ARMIDAH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 308, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 145, 121, 1 --DULCEC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 309, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 64, 121, 1 --LEONORH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 310, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 153, 121, 1  -- ANAC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 311, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 154, 121, 1  -- CAROLINAD

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 312, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 187, 121, 1 --ELENAP					AX:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 313, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 139, 121, 1 --AX					AX:20210625

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 314, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 198, 121, 1 --NALLELYC			AX: 20210707
--=========GRUPO PARA AUTORIZAR CAMBIOS EN INSPECCION  DE MATERIAL PANTALLA AUTORIZAR INSPECCION MATERIAL========================================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 401, 'QA MODIFICAR INSPECCION MATERIAL',					'FR@NC15C03', 144, 150, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 402, 'QA MODIFICAR INSPECCION MATERIAL',					'M16U31C4', 47, 150, 1 -- MIGUELC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 403, 'QA MODIFICAR INSPECCION MATERIAL',					'M4R105@', 129, 150, 1 -- MARIOS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 404, 'QA MODIFICAR INSPECCION MATERIAL',					'J012G3J@', 140, 150, 1 -- JORGEJ
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 405, 'QA MODIFICAR INSPECCION MATERIAL',					'J0R6301', 86, 150, 1 -- JORGEO
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 406, 'QA MODIFICAR INSPECCION MATERIAL',					'M@RL3N35', 162, 150, 1 -- MARLENNES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 407, 'QA MODIFICAR INSPECCION MATERIAL',					'41B@J@', 142, 150, 1 -- ALBAJ 

--=========GRUPO PARA NOTIFICAR QUE EL MATERIAL HA SIDO LIBERADO/RECHAZADO PARA DISPOSICION PANTALLA AUTORIZAR INSPECCION MATERIAL========================================
 -- USE BD_GENERAL
 --MQU
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 500, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 144, 200, 1 -- FEG
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 501, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 47, 200, 1 -- MIGUELC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 502, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 129, 200, 1 -- MARIOS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 503, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 140, 200, 1 -- JORGEJ
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 504, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 86, 200, 1 -- JORGEO
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 505, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 132, 200, 1 -- TERESAJ

--MHI
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 551, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 144, 180, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 552, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 56, 180, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 553, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 45, 180, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 554, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 87, 180, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 555, 'MHI/MQU NOTIFICAR MATERIAL LIBERADO/RECHASADO POR QA',					'MHI_MQU_LR', 98, 180, 1 -- MONICAG


-- =============================================== -- ===============================================
-- ================================= GRUPOS PARA NOTIFICACION DE PEDIDOS Y RECIBOS	================================== AX
-- =============================================== -- ===============================================
-- #7800- 'INSPEC_BPO',		#7801- 'REQUIS_BPO',	#7900- 'RECIBI_BPO'		#7901-	'RECEXC_BPO'
-- =================================			CREAR PO		   ==================================	
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 600, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 139,	7800, 1		-- AX				
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 601, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 144,	7800, 0		-- FEG				
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 602, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 47,	7800, 1		-- MIGUELC
--DELETE	GRUPO_APROBADOR
--WHERE	K_GRUPO_APROBADOR IN (501,602,622)			AX:	20210409 SE ELIMINARON LOS PERMISOS A MIGUELC A PETICIÓN DEL USUARIO.
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 603, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 129,	7800, 1		-- MARIOS			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 604, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 140,	7800, 1		-- JORGEJ			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 605, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 86,	7800, 1		-- JORGEO			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 606, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 132,	7800, 0		-- TERESAJ

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 607, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 142,	7800, 1		-- ALBAJ	--AX: 20210104
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 608, 'MATERIAL SIN PARAMETROS PARA INSPECCION',			'INSPEC_BPO', 162,	7800, 1		-- MARLENES	--AX: 20210104

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 610, 'REQUISICIÓN DE MATERIAL DE BLANKET_PO',			'REQUIS_BPO', 139,	7801, 1		-- AX
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 611, 'REQUISICIÓN DE MATERIAL DE BLANKET_PO',			'REQUIS_BPO', 56,	7801, 1		-- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 612, 'REQUISICIÓN DE MATERIAL DE BLANKET_PO',			'REQUIS_BPO', 87,	7801, 1		-- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 613, 'REQUISICIÓN DE MATERIAL DE BLANKET_PO',			'REQUIS_BPO', 159,	7801, 1		-- CARLAR	--AX: 20210126

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 620, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 139,	7900, 1		-- AX		DE AQUÍ SE ENVÍA NOTIFICACIÓN POR CORREO.
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 621, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 144,	7900, 1		-- FEG			
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 622, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 47,	7900, 1		-- MIGUELC			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 623, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 129,	7900, 1		-- MARIOS			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 624, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 140,	7900, 1		-- JORGEJ			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 625, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 86,	7900, 1		-- JORGEO			
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 626, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 132,	7900, 1		-- TERESAJ
		
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 627, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 142,	7900, 1		-- ALBAJ	--AX: 20210104
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 628, 'MATERIAL RECIBIDO PARA INSPECCIONAR',				'RECIBI_BPO', 162,	7900, 1		-- MARLENES	--AX: 20210104


EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 630, 'MATERIAL RECIBIDO CON EXCEDENTE',					'RECEXC_BPO', 139,	7901, 1		-- AX
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 631, 'MATERIAL RECIBIDO CON EXCEDENTE',					'RECEXC_BPO', 56,	7901, 1		-- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 632, 'MATERIAL RECIBIDO CON EXCEDENTE',					'RECEXC_BPO', 87,	7901, 1		-- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 633, 'MATERIAL RECIBIDO CON EXCEDENTE',					'RECEXC_BPO', 159,	7901, 1		-- CARLAR	--AX: 20210126


--=========POR EL MOMENTO NO SE USAN GRUPO PARA NOTIFICAR QUE EL MATERIAL HA SIDO LIBERADO/RECHAZADO PARA DISPOSICION PANTALLA AUTORIZAR INSPECCION MATERIAL========================================
--EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 300, 'ENVIAR_MATERIAL_A_QC',						'ENV_MAT_QC', 300, '', 1
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 700, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 45, 300, 1 -- PEDROV
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 701, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 87, 300, 1 -- DIANAN
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 702, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 98, 300, 1 -- MONICAG
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 703, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 159, 300, 1 -- KARLAR
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 704, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 77, 300, 1 -- GENARO
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 705, 'ENVIAR MATERIAL PARA REVISION QC/ REGRESAR A INVENTARIO',		'ENV_REV_QC', 131, 300, 1 -- JESUS
		
--		--EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 350, 'ENVIAR_MATERIAL_A_INVENTARIO',				'ENV_MAT_IN', 350, '', 1
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 750, 'QC REGRESAR MATERIAL A INVENTARIO EMBARQUE',					'ENV_REV_IN', 47,	350, 1		-- MIGUELC			
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 751, 'QC REGRESAR MATERIAL A INVENTARIO EMBARQUE',					'ENV_REV_IN', 129,	350, 1		-- MARIOS			
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 752, 'QC REGRESAR MATERIAL A INVENTARIO EMBARQUE',					'ENV_REV_IN', 140,	350, 1		-- JORGEJ			
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 753, 'QC REGRESAR MATERIAL A INVENTARIO EMBARQUE',					'ENV_REV_IN', 86,	350, 1		-- JORGEO			
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 754, 'QC REGRESAR MATERIAL A INVENTARIO EMBARQUE',					'ENV_REV_IN', 132,	350, 1		-- TERESAJ


-- =============================================== -- ===============================================
-- ================================= GRUPOS PARA NOTIFICACION COMPATIBILIDAD DE LOTES	================================== AX
-- =============================================== -- ===============================================
-- #9200- 'LOT_COMPAT'
-- =================================			CREACIÓN / MODIFICACIÓN		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 800, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 139,	9200, 1		-- AX: 20210301
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 801, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 129,	9200, 1		-- MARIO		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 802, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 132,	9200, 1		-- TERESAJ		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 803, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 86,	9200, 1		-- JORGEO		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 804, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 92,	9200, 1		-- JOSES		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 805, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 48,	9200, 1		-- IVAND		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 806, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 140,	9200, 1		-- JORGEJ		: 20210303
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 807, 'COMPATIBILIDAD LOTES',							'LOT_COMPAT', 173,	9200, 1		-- PEDROS		: 20210308
-- =============================================== -- ===============================================
-- =============================================== -- ===============================================

--	SELECT * FROM BD_GENERAL.DBO.GRUPO_APROBADOR	WHERE	K_GRUPO_APROBADOR=800		
--	DELETE	BD_GENERAL.DBO.GRUPO_APROBADOR	WHERE	K_GRUPO_APROBADOR=800		

--=========GRUPO AUTORIZADO PARA MODIFICAR/ELIMNAR ORDEN EN PANTALLA PLANNING========================================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1001, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 144, 400, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1002, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 56, 400, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1003, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 45, 400, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1004, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 87, 400, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1005, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 98, 400, 1 -- MONICAG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1006, 'MODIFICAR/ELIMINAR ORDEN EN PLANNING',			'UP_DL_ORD', 139, 400, 1 -- AX: 20210707

--=========GRUPO AUTORIZADO PARA LEER TICKET DE PIEL ORDEN EN PANTALLA IMPORT HIDE========================================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1101, 'LEER TICKES DE PIEL',					'LEE_TICKET', 144, 450, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1102, 'LEER TICKES DE PIEL',					'LEE_TICKET', 56, 450, 0 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1103, 'LEER TICKES DE PIEL',					'LEE_TICKET', 45, 450, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1104, 'LEER TICKES DE PIEL',					'LEE_TICKET', 87, 450, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1105, 'LEER TICKES DE PIEL',					'LEE_TICKET', 98, 450, 1 -- MONICAG	
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1106, 'LEER TICKES DE PIEL',					'LEE_TICKET', 90, 450, 1 -- TANIAC 

--=========GRUPO PARA MARCAR PIELES PARA DEVOLUCION EN MESAS========================================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1120, 'PRD DEVOLUCION/TRASPASO PIEL',					'ESTEBAN12', 13367, 500, 1 -- FEG

--=========GRUPO PARA TRASPASAR PIELES ENTRE ORDENES EN MESAS========================================
 -- USE BD_GENERAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1150, 'PRD DEVOLUCION/TRASPASO PIEL',					'ESTEBAN', 22, 550, 1 -- FEG

-- =============================================== -- ===============================================
-- ================================= NOTIFICACIONES INVENTARIO MATERIAL CONTROLADO	================================== AX
-- =============================================== -- ===============================================
-- ================================= CUANDO EL STOCK DE MATERIAL(PRODUCCIÓN) SE ENCUENTRA EN CANTIDADES MÍNIMAS.
-- #9600- 'STOCK_MIN_HILO'
-- =================================			CREACIÓN / MODIFICACIÓN		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1201, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 139,	9600, 0		-- AX			:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1202, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 56,	9600, 1		-- MANUELG		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1203, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 87,	9600, 1		-- DIANAN		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1204, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 44,	9600, 1		-- GUILLERMOM	:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1205, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 187,	9600, 1		-- ELENAP		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1206, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 41,	9600, 0		-- RAFA			:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1207, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 144,	9600, 0		-- FEG			:20210519

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1208, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 60,	9600, 1		-- ADRIANAD		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1209, 'NOTIFICACION MINIMOS DE HILO',							'STOCK_MIN_HILO', 57,	9600, 1		-- FABIOLAG		:20210610

-- ================================= CUANDO EL STOCK DE MATERIAL(PRODUCCIÓN) SE ENCUENTRA EN CANTIDADES MÍNIMAS.
-- #8300- 'STOCK_MIN_MULLL'
-- =================================			CREACIÓN / MODIFICACIÓN		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1250, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 139,	8300, 0		-- AX			:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1251, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 56,	8300, 1		-- MANUELG		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1252, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 87,	8300, 1		-- DIANAN		:20210519
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1253, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 44,	8300, 1		-- GUILLERMOM	:20210519
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1254, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 92,	8300, 1		-- ELENAP		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1255, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 41,	8300, 0		-- RAFA			:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1256, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 144,	8300, 0		-- FEG			:20210519

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1257, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 60,	8300, 1		-- ADRIANAD		:20210519
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1258, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 57,	8300, 1		-- FABIOLAG		:20210610
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1259, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 69,	8300, 0		-- MARIAS		:20210519
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1260, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 157,	8300, 0		-- BERENICES	:20210519
--EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1261, 'NOTIFICACION MINIMOS DE MULLER',							'STOCK_MIN_MULL', 161,	8300, 0		-- ANAM			:20210519


-- =============================================== -- ===============================================
-- ================================= CUANDO SE GENERA UNA ORDEN POR RECHAZO O POR UN PEDIDO ESPECIAL DE PARTE DEL CLIENTE.
-- #9703- ORDEN RMA / PES	GENERADA
-- =================================			CREACIÓN / MODIFICACIÓN		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1301, 'AUTORIZAR RMA/PES',							'AUTORIZAR RMA/PES', 139,	9703, 1		-- AX			:2021621
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1302, 'AUTORIZAR RMA/PES',							'AUTORIZAR RMA/PES', 47,	9703, 0		-- MIGUELC		:2021621
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1303, 'AUTORIZAR RMA/PES',							'AUTORIZAR RMA/PES', 43,	9703, 0		-- JORGEH		:2021621
-- ===============================================
SET NOCOUNT OFF
-- ===============================================

GO
SELECT * FROM USUARIO_PEARL


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
