-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		ALL
-- // MODULE:			COMBOBOX
-- // OPERATION:		GENERAR COMBOBOX
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			IT	
-- // CREATION DATE:	20200214
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO


/* CARGA COMBO DE LOCACIONES */
-- EXECUTE [PG_CB_IMLOCFIL_SQL] 001,144, 8
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_IMLOCFIL_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_IMLOCFIL_SQL]
GO


CREATE PROCEDURE [dbo].[PG_CB_IMLOCFIL_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS

	DECLARE @VP_TA_CATALOGO	AS TABLE
						(	TA_K_CATALOGO		INT IDENTITY(1,1) NOT NULL,
							TA_D_CATALOGO		VARCHAR(50))

	IF @PP_L_CON_TODOS=1
		BEGIN	
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(alt1_loc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql 
		END

	IF @PP_L_CON_TODOS=2
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(alt1_loc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(alt1_loc)),1,1) IN ('T', 'G')
			UNION
			SELECT	LTRIM(RTRIM(alt1_loc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql 
			WHERE	 LTRIM(RTRIM(alt1_loc)) = 'MHI'
		END

	IF @PP_L_CON_TODOS=3
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(alt1_loc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(alt1_loc)),1,1) NOT IN ('T', 'G','R', 'J', 'P') 
		END

	IF @PP_L_CON_TODOS=4
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(loc_desc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(loc_desc)),1,1) = 'T'
		END

	IF @PP_L_CON_TODOS=5
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(alt1_loc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)

			INSERT INTO @VP_TA_CATALOGO (TA_D_CATALOGO)
			VALUES ( '( TODOS )'	)
		END
		
	IF @PP_L_CON_TODOS=6 -- PARA LISTADO DE GENERAR ORDEN EN GERBER
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(loc_desc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(loc_desc)),1,1) = 'G'

			INSERT INTO @VP_TA_CATALOGO (TA_D_CATALOGO)
			VALUES ( '( TODOS )'	)
		END

	IF @PP_L_CON_TODOS=7 -- PARA FICHA DE GENERAR ORDEN EN GERBER
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(loc_desc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(loc_desc)),1,1) = 'G'

		END

	IF @PP_L_CON_TODOS=8
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	LTRIM(RTRIM(loc_desc))		AS D_COMBOBOX	
			FROM	DATA_02.DBO.imlocfil_sql (NOLOCK)
			WHERE	SUBSTRING(LTRIM(RTRIM(loc_desc)),1,1) IN ('T', 'G')

			INSERT INTO @VP_TA_CATALOGO (TA_D_CATALOGO)
			VALUES ( '( TODOS )'	)
		END

		-- ====================================================================================
		-- =======================		FO_INVENTARIO
		-- ====================================================================================
		--	PARA GENERAR COMBO DE LA FO_INVENTARIO, MUESTRA LAS LOCACIONES
	--IF @PP_L_CON_TODOS=10	OR	@PP_L_CON_TODOS=11
	--	BEGIN
	--		INSERT INTO @VP_TA_CATALOGO 
	--		SELECT	A4GLIDENTITY AS TA_K_CATALOGO,
	--				LTRIM(RTRIM(loc)) AS TA_D_CATALOGO
	--		FROM	[DATA_02].[dbo].imlocfil_sql
	--		WHERE	LTRIM(RTRIM(alt1_loc))=''
	--		ORDER BY TA_D_CATALOGO

			--	PARA GENERAR COMBO DE LA FO_INVENTARIO, MUESTRA LAS LOCACIONES CON EL TODOS CON (-1)
				--IF @PP_L_CON_TODOS=11
				--	BEGIN
				--		INSERT INTO @VP_TA_CATALOGO
				--			( TA_K_CATALOGO,	TA_D_CATALOGO	)
				--		VALUES
				--			( -1,				'( TODOS )'		)
				--	END
		--END
		-- ====================================================================================
		--SELECT * FROM [DATA_02].[dbo].imlocfil_sql
		-- ====================================================================================

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
			TA_D_CATALOGO	AS D_COMBOBOX 
	FROM	@VP_TA_CATALOGO
	ORDER BY  TA_D_CATALOGO 
		
	-- ////////////////////////////////////////////////////
GO


-- ////////////////////////////////////////////////////
-- //	CARGA COMBO DE LOCACIONES PARA LA FO_INVENTARIO
-- //	AX : 20201203
-- ////////////////////////////////////////////////////
-- EXECUTE [PG_CB_IMLOCFIL_INVENTARIO_SQL] 001,144, 10
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_IMLOCFIL_INVENTARIO_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_IMLOCFIL_INVENTARIO_SQL]
GO
CREATE PROCEDURE [dbo].[PG_CB_IMLOCFIL_INVENTARIO_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
		(	TA_K_CATALOGO		INT NOT NULL,
			TA_D_CATALOGO		VARCHAR(50)	)

	-- ====================================================================================
	-- =======================		FO_INVENTARIO
	-- ====================================================================================
	----	PARA GENERAR COMBO DE LA FO_INVENTARIO, MUESTRA LAS LOCACIONES
	INSERT INTO @VP_TA_CATALOGO 
	SELECT	A4GLIDENTITY AS TA_K_CATALOGO,
			LTRIM(RTRIM(loc)) AS TA_D_CATALOGO
	FROM	[DATA_02].[dbo].imlocfil_sql (NOLOCK)
	WHERE	LTRIM(RTRIM(alt1_type))=''
	AND		SUBSTRING(LTRIM(RTRIM(alt1_loc)),1,1) NOT IN ('T', 'G', 'R', 'J')
	AND		LOC NOT IN ('MCT','MEP','MFP','MHH','MIT','MOB','MOS','MRD','MTR')
	ORDER BY TA_D_CATALOGO
	--SELECT	*	FROM	[DATA_02].[dbo].imlocfil_sql
	----	PARA GENERAR COMBO DE LA FO_INVENTARIO, MUESTRA LAS LOCACIONES CON EL TODOS CON (-1)
	IF @PP_L_CON_TODOS = 1
	BEGIN
		INSERT INTO @VP_TA_CATALOGO
			( TA_K_CATALOGO,	TA_D_CATALOGO	)
		VALUES
			( -1,				'( TODOS )'		)
	END
	-- ====================================================================================
	--SELECT * FROM [DATA_02].[dbo].imlocfil_sql
	-- ====================================================================================

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
			TA_D_CATALOGO	AS D_COMBOBOX 
	FROM	@VP_TA_CATALOGO
	ORDER BY  TA_D_CATALOGO 
	-- ////////////////////////////////////////////////////
GO		


-- //////////////////////////////////////////////////////////////
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 0
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 1
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 2
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 3
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 4
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 5
-- EXECUTE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL] 0,0, 6
-- //////////////////////////////////////////////////////////////
-- // /* CARGA COMBO DE CLIENTES */
-- //////////////////////////////////////////////////////////////
-- USE [BD_GENERAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL]
GO
CREATE PROCEDURE [dbo].[PG_CB_CUSTOMER_ARCUSFIL_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT,
					TA_L_DELETED		INT,	
					TA_L_ACTIVO			INT			 )
	
	-- COMBO NORMAL DE CLIENTES	(0=COMBO PARA LAS FICHAS, 1=INCLUYEN EL REGISTRO DE ALL)
	--	(0)FO_PURCHASE_ORDER
	--	(0)FO_PO_REVIEW
	--	(1)FO_APQP_MODEL
	--	(1)FO_FACTURA_COBRADA
	--	(1)FO_ORDEN_GERBER
	IF @PP_L_CON_TODOS IN (0,1)
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY AS TA_K_CATALOGO,
					LTRIM(RTRIM(CUS_NO)) AS TA_D_CATALOGO, 
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02].[dbo].ARCUSFIL_SQL (NOLOCK)
			WHERE	L_BORRADO=0
			AND		L_ARCUSFIL=1
			ORDER BY TA_D_CATALOGO
		END

	-- SE USA EN PANTALLA FO_PACKING_NO
	IF @PP_L_CON_TODOS=2
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(CUS_NO))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			ORDER BY TA_D_CATALOGO 
		END
	
	-- SE USA EN LA FO_COTIZACIONES PARA MOSTRAR LOS CLIENTES INCLUIDOS EN 	ALGUNA COTIZACIÓN
	--	FO_ENG_QUOTE
	IF @PP_L_CON_TODOS=3
	BEGIN
		INSERT INTO @VP_TA_CATALOGO 
		SELECT	DISTINCT
				ARCUSFIL_SQL.A4GLIdentity	,
				CCVERHDR_SQL.CUS_NO			,
				1,--ARCUSFIL_SQL.O_ARCUSFIL		,
				ARCUSFIL_SQL.L_BORRADO		,
				ARCUSFIL_SQL.L_ARCUSFIL		
		FROM	[DATA_02].[dbo].CCVERHDR_SQL		(NOLOCK),
				[DATA_02].[dbo].ARCUSFIL_SQL		(NOLOCK)
		WHERE	CCVERHDR_SQL.STATUS			= 'L'
		AND		CCVERHDR_SQL.SPECSTATUS		= 'U'
		AND		ARCUSFIL_SQL.CUS_NO			= CCVERHDR_SQL.cus_no
		ORDER BY CCVERHDR_SQL.CUS_NO
		--SELECT	DISTINCT(A4GLIDENTITY) AS TA_K_CATALOGO,
		--		LTRIM(RTRIM(CUS_NO)) AS TA_D_CATALOGO, 
		--		0 AS TA_O_CATALOGO,
		--		0 AS L_DELETED, 
		--		1 AS L_ACTIVO
		--FROM	[DATA_02].[dbo].ARCUSFIL_SQL, COT19_Cotizaciones_V9999_R0.DBO.QUOTE
		--WHERE	K_CUSTOMER=A4GLIDENTITY
		--AND		ARCUSFIL_SQL.L_BORRADO=0
		--AND		L_ARCUSFIL=1
		--ORDER BY TA_D_CATALOGO
	END

	--	PARA INDICAR LOS CLIENTES CARGADOS EN LOS PROGRAMAS.
	-- FO_ARCUSFIL_PROGRAM
	IF @PP_L_CON_TODOS=4
	BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT 
					--ARCUSFIL_PROGRAM.A4GLIDENTITY AS TA_K_CATALOGO,
					ARCUSFIL_PROGRAM.K_ARCUSFIL AS TA_K_CATALOGO,
					LTRIM(RTRIM(CUS_NO)) AS TA_D_CATALOGO,
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02Pruebas].[dbo].ARCUSFIL_PROGRAM, [DATA_02].DBO.ARCUSFIL_SQL
			WHERE	ARCUSFIL_PROGRAM.K_ARCUSFIL			= ARCUSFIL_SQL.A4GLIDENTITY
			AND		ARCUSFIL_PROGRAM.L_BORRADO			= 0
			AND		ARCUSFIL_PROGRAM.L_ARCUSFIL_PROGRAM	= 1
			ORDER BY TA_D_CATALOGO
	END

	--	PARA CARGAR LOS CLIENTES DEL SISTEMA.
	-- KIT_MASTER
	IF @PP_L_CON_TODOS=5
	BEGIN
			DECLARE @VP_TA_CATALOGO_2	AS TABLE
				(	TA_K_CATALOGO		VARCHAR(50),
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT,
					TA_L_DELETED		INT,	
					TA_L_ACTIVO			INT			 )
		
			INSERT INTO @VP_TA_CATALOGO_2
			SELECT	
					A4GLIdentity AS TA_K_CATALOGO,
					CUS_NO AS TA_D_CATALOGO,
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02].DBO.ARCUSFIL_SQL (NOLOCK)
			WHERE	L_BORRADO=0
			AND		L_ARCUSFIL=1
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO_2
				( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
			VALUES
				( -1,				'( SELECT )',	-999,		   0,			 1				)
			
			SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
					TA_D_CATALOGO	AS D_COMBOBOX 
			FROM	@VP_TA_CATALOGO_2
			ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 
	END	
	
	-- SE USA EN PANTALLA FO_SUMARY_INVOICE
	IF @PP_L_CON_TODOS=6
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(CUS_NO))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			ORDER BY TA_D_CATALOGO 
		END

	IF @PP_L_CON_TODOS	IN	(1,2,4)--(1,2,3,4)	AX:20210329
	BEGIN
			INSERT INTO @VP_TA_CATALOGO
				( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
			VALUES
				( -1,				'( TODOS )',	-999,		   0,			 1				)
	END



	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
			TA_D_CATALOGO	AS D_COMBOBOX 
	FROM	@VP_TA_CATALOGO
	ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 
	-- ==========================================		
	-- ////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////

-- SELECT * FROM	[DATA_02].[dbo].IMCATFIL_SQL WHERE A4GLIDENTITY = 212
-- EXECUTE [dbo].[PG_CB_PRODUCT_CATEGORY_IMCATFIL_SQL] 0,0, 0
-- //////////////////////////////////////////////////////////////
-- // /* CARGA COMBO DE PRODUCT_CATEGORY */
-- //////////////////////////////////////////////////////////////
-- USE [BD_GENERAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_PRODUCT_CATEGORY_IMCATFIL_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_PRODUCT_CATEGORY_IMCATFIL_SQL]
GO


CREATE PROCEDURE [dbo].[PG_CB_PRODUCT_CATEGORY_IMCATFIL_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT,
					TA_L_DELETED		INT,	
					TA_L_ACTIVO			INT			 )
	

	IF @PP_L_CON_TODOS=0
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
					LTRIM(RTRIM(PROD_CAT))	AS TA_D_CATALOGO, 
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02].[dbo].IMCATFIL_SQL (NOLOCK)
			WHERE	PROD_CAT_DESC<>'OBSOLETE' 
			AND		PROD_CAT_DESC<>'DO NOT DELETE'
			ORDER BY TA_D_CATALOGO
		END

	IF @PP_L_CON_TODOS=1
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
					LTRIM(RTRIM(PROD_CAT))	AS TA_D_CATALOGO, 
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02].[dbo].IMCATFIL_SQL (NOLOCK)
			WHERE	PROD_CAT_DESC<>'OBSOLETE' 
			AND		PROD_CAT_DESC<>'DO NOT DELETE'
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'( TODOS )',	-999,		   0,			 1				)
		END

	-- SE USA EN PANTALLA FO_PACKING SE MUESTRA LA DESCRIPCION DE LA PROD. CATEGORY
	IF @PP_L_CON_TODOS=2
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
					LTRIM(RTRIM(PROD_CAT_DESC))	AS TA_D_CATALOGO, 
					0 AS TA_O_CATALOGO,
					0 AS L_DELETED, 
					1 AS L_ACTIVO
			FROM	[DATA_02].[dbo].IMCATFIL_SQL (NOLOCK)
			WHERE	PROD_CAT_DESC <> 'OBSOLETE' 
			AND		PROD_CAT_DESC <> 'DO NOT DELETE'
			AND		A4GLIDENTITY <> 212
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'( TODOS )',	-999,		   0,			 1				)
		END

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 
	-- ==========================================		
	-- ////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // /* CARGA COMBO DE COLORES */
-- //////////////////////////////////////////////////////////////
-- EXECUTE [dbo].[PG_CB_COLOR_IMITMIDX_SQL] 1, 144, 4
-- USE [BD_GENERAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_COLOR_IMITMIDX_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_COLOR_IMITMIDX_SQL]
GO


CREATE PROCEDURE [dbo].[PG_CB_COLOR_IMITMIDX_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT,
					TA_L_DELETED		INT,	
					TA_L_ACTIVO			INT			 )
		-- ==========================================

	IF @PP_L_CON_TODOS=0
	INSERT INTO @VP_TA_CATALOGO 
	SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
			LTRIM(RTRIM(ITEM_NO))	AS TA_D_CATALOGO,
			0						AS TA_O_CATALOGO,
			0						AS L_DELETED, 
			1						AS L_ACTIVO
	FROM [DATA_02].[dbo].IMITMIDX_SQL (NOLOCK)
	WHERE ITEM_NO LIKE 'F%'
	AND LEN(RTRIM(LTRIM(ITEM_NO)))=7
	ORDER BY TA_D_CATALOGO 

	-- ==========================================
	IF @PP_L_CON_TODOS=1
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
					LTRIM(RTRIM(ITEM_NO))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].IMITMIDX_SQL (NOLOCK)
			WHERE ITEM_NO LIKE 'F%'
			AND LEN(RTRIM(LTRIM(ITEM_NO)))=7
			ORDER BY TA_D_CATALOGO 

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'( TODOS )',	-999,		   0,			 1				)

		END
			-- ==========================================

		IF @PP_L_CON_TODOS=2
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
					LTRIM(RTRIM(ITEM_NO))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].IMITMIDX_SQL (NOLOCK)
			WHERE ITEM_NO IN (SELECT COLOR FROM [DATA_02].DBO.COLORES_CONTROLADOS (NOLOCK) WHERE COLOR <> 'FMCKSTT')
			AND LEN(RTRIM(LTRIM(ITEM_NO)))=7
			ORDER BY TA_D_CATALOGO 

			--SELECT	DISTINCT
			--		1			AS TA_K_CATALOGO,
			--		LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
			--		0						AS TA_O_CATALOGO,
			--		0						AS L_DELETED, 
			--		1						AS L_ACTIVO
			--FROM [DATA_02].[dbo].COLORES_ACTIVOS 
			--ORDER BY TA_D_CATALOGO 
			-- ==========================================

		IF @PP_L_CON_TODOS=3
		INSERT INTO @VP_TA_CATALOGO 
		SELECT	A4GLIDENTITY			AS TA_K_CATALOGO,
				LTRIM(RTRIM(ITEM_NO))	AS TA_D_CATALOGO,
				0						AS TA_O_CATALOGO,
				0						AS L_DELETED, 
				1						AS L_ACTIVO
		FROM [DATA_02].[dbo].IMITMIDX_SQL (NOLOCK)
		WHERE ITEM_NO LIKE 'F%'
		AND LEN(RTRIM(LTRIM(ITEM_NO)))=7
		ORDER BY TA_D_CATALOGO 
			-- ==========================================
		
		-- COMBO UTILIZADO EN PANTALLA IMPORT HIDE
		IF @PP_L_CON_TODOS=4
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			ORDER BY TA_D_CATALOGO 

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( 1,				'FGMPAD4',	0,		   0,			 1				)

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( 1,				'FGMPAA6',	0,		   0,			 1				)

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( 1,				'FCSL5B8',	0,		   0,			 1				)

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( 1,				'FCSLARC',	0,		   0,			 1				)

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'(Seleccione Color)',	-999,		   0,			 1				)

		END
			-- ==========================================

		-- COMBO UTILIZADO EN PANTALLA MATERIAL LABELS
		IF @PP_L_CON_TODOS=5
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			WHERE LTRIM(RTRIM(COLOUR)) NOT IN ( SELECT COLOR FROM [DATA_02].DBO.COLORES_CONTROLADOS (NOLOCK) )
			ORDER BY TA_D_CATALOGO 

			
			--INSERT INTO @VP_TA_CATALOGO
			--		( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
			--	VALUES
			--		( 1,				'FGMPAD4',	0,		   0,			 1				)

			--INSERT INTO @VP_TA_CATALOGO
			--		( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
			--	VALUES
			--		( 1,				'FGMPAA6',	0,		   0,			 1				)

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'',	-999,		   0,			 1				)

		END
			-- ==========================================

		-- COMBO UTILIZADO EN PANTALLA FO_PACKING
		IF @PP_L_CON_TODOS=6
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			ORDER BY TA_D_CATALOGO 

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO, TA_L_DELETED, TA_L_ACTIVO	)
				VALUES
					( -1,				'( TODOS )',	-999,		   0,			 1				)

		END
			-- ==========================================

		-- COMBO UTILIZA EN PANTALLA FO_PLANNING
		IF @PP_L_CON_TODOS=7
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT	DISTINCT
					1			AS TA_K_CATALOGO,
					LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
					0						AS TA_O_CATALOGO,
					0						AS L_DELETED, 
					1						AS L_ACTIVO
			FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
			ORDER BY TA_D_CATALOGO 
		END
			-- ==========================================

		-- SE UTILIZA EN PANTALLA FOLIOSV2 PARA COMBO DE CAMBIO DE COLOR
		IF @PP_L_CON_TODOS=8
			BEGIN
				INSERT INTO @VP_TA_CATALOGO 
				SELECT	DISTINCT
						1			AS TA_K_CATALOGO,
						LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
						0						AS TA_O_CATALOGO,
						0						AS L_DELETED, 
						1						AS L_ACTIVO
				FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
				ORDER BY TA_D_CATALOGO 

				INSERT INTO @VP_TA_CATALOGO 
				SELECT	1,
						'FWLROT3',
						0,
						0,
						1
			END

		SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	

	-- ==========================================
	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO





-- USE BD_GENERAL
-- EXECUTE [dbo].[PG_CB_PIEL_CLASIFICACION] 0,0, 1
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_PIEL_CLASIFICACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_PIEL_CLASIFICACION]
GO


CREATE PROCEDURE [dbo].[PG_CB_PIEL_CLASIFICACION]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT
					)
	
	INSERT INTO @VP_TA_CATALOGO 
	SELECT	K_PIEL_CLASIFICACION AS TA_K_CATALOGO,
			D_PIEL_CLASIFICACION AS TA_D_CATALOGO, 
			O_PIEL_CLASIFICACION AS TA_O_CATALOGO
	FROM	[DATA_02].[dbo].PIEL_CLASIFICACION (NOLOCK)
	ORDER BY TA_D_CATALOGO

	IF @PP_L_CON_TODOS=1
		INSERT INTO @VP_TA_CATALOGO
				( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO)
			VALUES
				( -1,				'( TODOS )',	-999			)

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- EXECUTE [dbo].[PG_CB_SYSCDEFIL_SQL] 0,0, 1
-- //////////////////////////////////////////////////////////////
-- // /* CODIGO UTILIZACION */ sycdefil_sql
-- //////////////////////////////////////////////////////////////
--	USE [BD_GENERAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_SYSCDEFIL_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_SYSCDEFIL_SQL]
GO


CREATE PROCEDURE [dbo].[PG_CB_SYSCDEFIL_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50)
							 )
	
	INSERT INTO @VP_TA_CATALOGO 
	SELECT	A4GLIDENTITY AS TA_K_CATALOGO,
			CONCAT(LTRIM(RTRIM(sy_terms_cd)), ' - ', LTRIM(RTRIM(filler_0001))) AS TA_D_CATALOGO
	FROM	[DATA_02].[dbo].sycdefil_sql (NOLOCK)
	WHERE	cd_type = 'R' 
	AND		sy_terms_cd LIKE 'H%' 
	ORDER BY	sy_terms_cd

	IF @PP_L_CON_TODOS=1
		INSERT INTO @VP_TA_CATALOGO
				( TA_K_CATALOGO,	TA_D_CATALOGO)
			VALUES
				( -1,				'( TODOS )')

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
			TA_D_CATALOGO	AS D_COMBOBOX 
	FROM	@VP_TA_CATALOGO
	ORDER BY  TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO



-- USE BD_GENERAL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_ITEM_INSPECCION_CONFIGURADA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_ITEM_INSPECCION_CONFIGURADA]
GO
/*
 EXECUTE [dbo].[PG_CB_ITEM_INSPECCION_CONFIGURADA] 0,0, 0
*/
CREATE PROCEDURE [dbo].[PG_CB_ITEM_INSPECCION_CONFIGURADA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT
					)
	
	IF @PP_L_CON_TODOS=0
	INSERT INTO @VP_TA_CATALOGO 
	SELECT DISTINCT	ITEM.K_ITEM AS TA_K_CATALOGO,
			PART_NUMBER_ITEM_PEARL AS TA_D_CATALOGO, 
			O_ITEM AS TA_O_CATALOGO
	FROM	COMPRAS.dbo.ITEM (NOLOCK)
	INNER JOIN [DATA_02].[dbo].INSPECCION_MATERIAL (NOLOCK) ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
	ORDER BY TA_D_CATALOGO

	IF @PP_L_CON_TODOS=1
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT DISTINCT	ITEM.K_ITEM AS TA_K_CATALOGO,
					PART_NUMBER_ITEM_PEARL AS TA_D_CATALOGO, 
					O_ITEM AS TA_O_CATALOGO
			FROM	COMPRAS.dbo.ITEM (NOLOCK)
			INNER JOIN [DATA_02].[dbo].INSPECCION_MATERIAL (NOLOCK) ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO)
				VALUES
					( -1,				'( TODOS )',	-999			)
		END

	IF @PP_L_CON_TODOS=2 -- MATERIAL DIFERENTE DE PIEL
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT DISTINCT	ITEM.K_ITEM AS TA_K_CATALOGO,
					PART_NUMBER_ITEM_PEARL AS TA_D_CATALOGO, 
					O_ITEM AS TA_O_CATALOGO
			FROM	COMPRAS.dbo.ITEM (NOLOCK)
					--COMPRAS_Pruebas.dbo.ITEM 
			INNER JOIN [DATA_02].[dbo].INSPECCION_MATERIAL (NOLOCK) ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
					--INNER JOIN [DATA_02PRUEBAS].[dbo].INSPECCION_MATERIAL ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
				AND		K_CLASS_ITEM = 2
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO)
				VALUES
					( -1,				'( TODOS )',	-999			)
		END

	IF @PP_L_CON_TODOS=3 -- MATERIAL QUE ES PIEL
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT DISTINCT	ITEM.K_ITEM AS TA_K_CATALOGO,
					PART_NUMBER_ITEM_PEARL AS TA_D_CATALOGO, 
					O_ITEM AS TA_O_CATALOGO
			FROM	COMPRAS.dbo.ITEM (NOLOCK)
			INNER JOIN [DATA_02].[dbo].INSPECCION_MATERIAL (NOLOCK) ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
			--COMPRAS_Pruebas.dbo.ITEM  
			--INNER JOIN [DATA_02PRUEBAS].[dbo].INSPECCION_MATERIAL ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
				AND		K_CLASS_ITEM = 3
			ORDER BY TA_D_CATALOGO

			INSERT INTO @VP_TA_CATALOGO
					( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO)
				VALUES
					( -1,				'( TODOS )',	-999			)
		END



	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO



-- USE BD_GENERAL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_HIDESHDR_SQL_TYPE]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_HIDESHDR_SQL_TYPE]
GO
/*
 EXECUTE [dbo].[PG_CB_HIDESHDR_SQL_TYPE] 0,0, 1
*/
CREATE PROCEDURE [dbo].[PG_CB_HIDESHDR_SQL_TYPE]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT IDENTITY (1,1),
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT DEFAULT 1
					)
	
	IF @PP_L_CON_TODOS=1
		INSERT INTO @VP_TA_CATALOGO 
		SELECT	DISTINCT
						LTRIM(RTRIM(COLOUR))	AS TA_D_CATALOGO,
						0						AS TA_O_CATALOGO
						
		FROM [DATA_02].[dbo].COLORES_ACTIVOS (NOLOCK)
		ORDER BY TA_D_CATALOGO 


	--IF @PP_L_CON_TODOS=1
	--INSERT INTO @VP_TA_CATALOGO 
	--SELECT	DISTINCT LTRIM(RTRIM(TYPE)) , 0
	--FROM	[DATA_02].[dbo].HIDESHDR_SQL 
	--WHERE	[TYPE] IS NOT NULL

	--IF @PP_L_CON_TODOS=1
	--	INSERT INTO @VP_TA_CATALOGO 
	--	SELECT DISTINCT
	--			LTRIM(RTRIM(search_desc))	AS TA_D_CATALOGO,
	--			0
	--	FROM [DATA_02].[dbo].IMITMIDX_SQL 
	--	WHERE ITEM_NO LIKE 'F%'
	--	AND LEN(RTRIM(LTRIM(ITEM_NO)))=7
	--	ORDER BY TA_D_CATALOGO 
			-- ==========================================
	--IF @PP_L_CON_TODOS=1
	--	INSERT INTO @VP_TA_CATALOGO
	--			( TA_K_CATALOGO,	TA_D_CATALOGO,	TA_O_CATALOGO)
	--		VALUES
	--			( -1,				'( TODOS )',	-999			)

	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO




-- USE BD_GENERAL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_IMPRESORA_ETIQUETA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_IMPRESORA_ETIQUETA]
GO
/*
 EXECUTE [dbo].[PG_CB_IMPRESORA_ETIQUETA] 0,0, 1
*/
CREATE PROCEDURE [dbo].[PG_CB_IMPRESORA_ETIQUETA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT IDENTITY (1,1),
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT DEFAULT 1
					)

	IF @PP_L_CON_TODOS=1
		BEGIN
			INSERT INTO @VP_TA_CATALOGO 
			SELECT 'Datamax #1' , 1

			INSERT INTO @VP_TA_CATALOGO 
			SELECT 'Datamax #2' , 2

			INSERT INTO @VP_TA_CATALOGO 
			SELECT 'Datamax #3' , 3
		END

	-- ==========================================	
	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO




-- USE BD_GENERAL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CB_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CB_TURNO]
GO
/*
 EXECUTE [dbo].[PG_CB_TURNO] 0,0, 1
*/
CREATE PROCEDURE [dbo].[PG_CB_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO				INT,
	--============================
	@PP_L_CON_TODOS				INT
AS
	DECLARE @VP_TA_CATALOGO	AS TABLE
				(	TA_K_CATALOGO		INT,
					TA_D_CATALOGO		VARCHAR(50),
					TA_O_CATALOGO		INT 
					)
					
	INSERT INTO @VP_TA_CATALOGO 
	SELECT 1, 'Turno 1', 1

	INSERT INTO @VP_TA_CATALOGO 
	SELECT 2, 'Turno 2', 2

	INSERT INTO @VP_TA_CATALOGO 
	SELECT 3, 'Turno 3', 3

	IF @PP_L_CON_TODOS=1
		INSERT INTO @VP_TA_CATALOGO
		SELECT	-1, '( TODOS )', -1 

	-- ==========================================	
	SELECT	TA_K_CATALOGO	AS K_COMBOBOX,
				TA_D_CATALOGO	AS D_COMBOBOX 
		FROM	@VP_TA_CATALOGO
		ORDER BY TA_O_CATALOGO, TA_D_CATALOGO 

	-- ==========================================
		
	-- ////////////////////////////////////////////////////
GO
