-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	RH
-- // MODULO:			
-- // OPERACION:		GRUPO_APROBADOR DESCRIPCION
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	04/FEB/2020
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[GRUPO_APROBADOR]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTATUS_GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[ESTATUS_GRUPO_APROBADOR]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_GRUPO_APROBADOR]') AND type in (N'U'))
	DROP TABLE [dbo].[TIPO_GRUPO_APROBADOR]
GO


-- //////////////////////////////////////////////////////////////
-- // TIPO_GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[TIPO_GRUPO_APROBADOR] (
	[K_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[D_TIPO_GRUPO_APROBADOR]	[VARCHAR] (100) NOT NULL,
	[S_TIPO_GRUPO_APROBADOR]	[VARCHAR] (20)	NOT NULL,
	[O_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[C_TIPO_GRUPO_APROBADOR]	[VARCHAR] (255) NOT NULL,
	[L_TIPO_GRUPO_APROBADOR]	[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////////////
ALTER TABLE [dbo].[TIPO_GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_TIPO_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_TIPO_GRUPO_APROBADOR])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_TIPO_GRUPO_APROBADOR_01_DESCRIPCION] 
	   ON [dbo].[TIPO_GRUPO_APROBADOR] ( [D_TIPO_GRUPO_APROBADOR] )
GO
-- //////////////////////////////////////////////////////////////
--ALTER TABLE [dbo].[TIPO_GRUPO_APROBADOR] ADD 
--	CONSTRAINT [FK_TIPO_GRUPO_APROBADOR_01] 
--		FOREIGN KEY ( [L_TIPO_GRUPO_APROBADOR] ) 
--		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
--GO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_TIPO_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR]
GO
CREATE PROCEDURE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_TIPO_GRUPO_APROBADOR	INT,
	@PP_D_TIPO_GRUPO_APROBADOR	VARCHAR(100),
	@PP_S_TIPO_GRUPO_APROBADOR	VARCHAR(20),
	@PP_O_TIPO_GRUPO_APROBADOR	INT,
	@PP_C_TIPO_GRUPO_APROBADOR	VARCHAR(255),
	@PP_L_TIPO_GRUPO_APROBADOR	INT
AS
	-- ===============================
	DECLARE @VP_K_EXISTE	INT
	SELECT	@VP_K_EXISTE =	K_TIPO_GRUPO_APROBADOR
							FROM	TIPO_GRUPO_APROBADOR
							WHERE	K_TIPO_GRUPO_APROBADOR=@PP_K_TIPO_GRUPO_APROBADOR
	-- ===============================
	IF @VP_K_EXISTE IS NULL
		INSERT INTO TIPO_GRUPO_APROBADOR	
			(	K_TIPO_GRUPO_APROBADOR,				D_TIPO_GRUPO_APROBADOR, 
				S_TIPO_GRUPO_APROBADOR,				O_TIPO_GRUPO_APROBADOR,
				C_TIPO_GRUPO_APROBADOR,
				L_TIPO_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_TIPO_GRUPO_APROBADOR,			@PP_D_TIPO_GRUPO_APROBADOR,	
				@PP_S_TIPO_GRUPO_APROBADOR,			@PP_O_TIPO_GRUPO_APROBADOR,
				@PP_C_TIPO_GRUPO_APROBADOR,
				@PP_L_TIPO_GRUPO_APROBADOR			)
	ELSE
		UPDATE	TIPO_GRUPO_APROBADOR
		SET		D_TIPO_GRUPO_APROBADOR	= @PP_D_TIPO_GRUPO_APROBADOR,	
				S_TIPO_GRUPO_APROBADOR	= @PP_S_TIPO_GRUPO_APROBADOR,			
				O_TIPO_GRUPO_APROBADOR	= @PP_O_TIPO_GRUPO_APROBADOR,
				C_TIPO_GRUPO_APROBADOR	= @PP_C_TIPO_GRUPO_APROBADOR,
				L_TIPO_GRUPO_APROBADOR	= @PP_L_TIPO_GRUPO_APROBADOR	
		WHERE	K_TIPO_GRUPO_APROBADOR=@PP_K_TIPO_GRUPO_APROBADOR
	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////
-- ===============================================
SET NOCOUNT ON
-- ===============================================

--=========PARA DESCRIPCION DE PUESTOS========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 1, 'CREAR DESCRIPCION PUESTO',		'CREA_DP', 1, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 2, 'AUTORIZAR DESCRIPCION PUESTO',	'AUTOR_DP', 2, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 3, 'NOTIFICAR DESCRIPCION PUESTO',	'NOTIF_DP', 3, '', 1

--=========PARA MQU SALIDA PANTALLA FOLIOS TX7========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 21, 'MQU SALIDA',					'MQU_SAL', 21, '', 1

--=========PARA MFP ENTRADA PANTALLA FOLIOS TX7========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 41, 'MFP NOTIFICAR ENTRADA',		'MFP_NOT_ENT', 41, '', 1

--=========PARA TRANSFERIR ORDEN COMPLETADA PANTALLA Transferencias========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 61, 'TRANSFERIR ORDEN COMPLETA',	'TRA_ORD_C',	61, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 62, 'TRANSFERIR ORDEN TX7',		'TRA_ORD_TX7',	62, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 63, 'LOTE NO COMPATIBLE',			'LOT_NO_COMP',	63, '', 1

--=========PARA TRANSFERIR ORDEN COMPLETADA PANTALLA IncInsp========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 81, 'MODIFCAR ESTATUS REPORTE',	'MOD_EST_RPT',	81, '', 1

--=========PARA SELECCIONAR TODOS LOS KITS PANTALLA frmKits========================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 101, 'SELECCIONAR TODO',			'SELEC_TODO',	101, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 102, 'ABRIR ORDEN',				'ABR_ORD',		102, '', 1

--=========PARA CERRAR ORDEN PANTALLA FORMLOTS========================================
-- SELECT * FROM TIPO_GRUPO_APROBADOR
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 121, 'CERRAR ORDEN',				'CERR_ORD', 121, '', 1

-- =============================================== -- ===============================================
-- ================================= GRUPOS APROBADORES PARA PO	================================== AX
-- =============================================== -- ===============================================
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6001, 'CREAR PO',					'CREAR_PO',	6001, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6002, 'AUTORIZAR PO',				'AUTOR_PO', 6002, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6003, 'NOTIFICAR PO',				'NOTIF_PO', 6003, '', 1
EXECUTE [dbo].[PG_CI_TIPO_GRUPO_APROBADOR] 0, 0, 6004, 'IMPRIMIR PO',				'IMPRI_PO', 6003, '', 1
GO
-- ===============================================
SET NOCOUNT OFF
-- ===============================================



-- //////////////////////////////////////////////////////////////
-- // ESTATUS_GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////


CREATE TABLE [dbo].[ESTATUS_GRUPO_APROBADOR] (
	[K_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[D_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (100) NOT NULL,
	[S_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (10)	NOT NULL,
	[O_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL,
	[C_ESTATUS_GRUPO_APROBADOR]	[VARCHAR] (255) NOT NULL,
	[L_ESTATUS_GRUPO_APROBADOR]	[INT]			NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_ESTATUS_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_ESTATUS_GRUPO_APROBADOR])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ESTATUS_GRUPO_APROBADOR_01_DESCRIPCION] 
	   ON [dbo].[ESTATUS_GRUPO_APROBADOR] ( [D_ESTATUS_GRUPO_APROBADOR] )
GO

-- //////////////////////////////////////////////////////////////


--ALTER TABLE [dbo].[ESTATUS_GRUPO_APROBADOR] ADD 
--	CONSTRAINT [FK_ESTATUS_GRUPO_APROBADOR_01] 
--		FOREIGN KEY ( [L_ESTATUS_GRUPO_APROBADOR] ) 
--		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
--GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]
GO


CREATE PROCEDURE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_ESTATUS_GRUPO_APROBADOR	INT,
	@PP_D_ESTATUS_GRUPO_APROBADOR	VARCHAR(100),
	@PP_S_ESTATUS_GRUPO_APROBADOR	VARCHAR(10),
	@PP_O_ESTATUS_GRUPO_APROBADOR	INT,
	@PP_C_ESTATUS_GRUPO_APROBADOR	VARCHAR(255),
	@PP_L_ESTATUS_GRUPO_APROBADOR	INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_ESTATUS_GRUPO_APROBADOR
							FROM	ESTATUS_GRUPO_APROBADOR
							WHERE	K_ESTATUS_GRUPO_APROBADOR=@PP_K_ESTATUS_GRUPO_APROBADOR

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO ESTATUS_GRUPO_APROBADOR	
			(	K_ESTATUS_GRUPO_APROBADOR,				D_ESTATUS_GRUPO_APROBADOR, 
				S_ESTATUS_GRUPO_APROBADOR,				O_ESTATUS_GRUPO_APROBADOR,
				C_ESTATUS_GRUPO_APROBADOR,
				L_ESTATUS_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_ESTATUS_GRUPO_APROBADOR,			@PP_D_ESTATUS_GRUPO_APROBADOR,	
				@PP_S_ESTATUS_GRUPO_APROBADOR,			@PP_O_ESTATUS_GRUPO_APROBADOR,
				@PP_C_ESTATUS_GRUPO_APROBADOR,
				@PP_L_ESTATUS_GRUPO_APROBADOR			)
	ELSE
		UPDATE	ESTATUS_GRUPO_APROBADOR
		SET		D_ESTATUS_GRUPO_APROBADOR	= @PP_D_ESTATUS_GRUPO_APROBADOR,	
				S_ESTATUS_GRUPO_APROBADOR	= @PP_S_ESTATUS_GRUPO_APROBADOR,			
				O_ESTATUS_GRUPO_APROBADOR	= @PP_O_ESTATUS_GRUPO_APROBADOR,
				C_ESTATUS_GRUPO_APROBADOR	= @PP_C_ESTATUS_GRUPO_APROBADOR,
				L_ESTATUS_GRUPO_APROBADOR	= @PP_L_ESTATUS_GRUPO_APROBADOR	
		WHERE	K_ESTATUS_GRUPO_APROBADOR=@PP_K_ESTATUS_GRUPO_APROBADOR

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////




-- ===============================================
SET NOCOUNT ON
-- ===============================================

EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 0, 'INACTIVO',			'INACTVO', 0, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 1, 'ACTIVO',			'ACTIVO', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 2, 'SUSPENDIDO',		'SUSPNDO', 2, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 3, 'APROBADO',		'APROB', 3, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 4, 'CANCELADO',		'CANCEL', 4, '', 1
--EXECUTE [dbo].[PG_CI_ESTATUS_GRUPO_APROBADOR] 0, 0, 4, 'VENCIDO',			'CANCEL', 4, '', 1

GO
-- ===============================================
SET NOCOUNT OFF
-- ===============================================




-- //////////////////////////////////////////////////////////////
-- // GRUPO_APROBADOR
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[GRUPO_APROBADOR] (
	[K_GRUPO_APROBADOR]				[INT]			NOT NULL,
	-- =================================	
	[D_GRUPO_APROBADOR]				VARCHAR(100)	NOT NULL,	
	[S_GRUPO_APROBADOR]				VARCHAR(50)		NOT NULL,
	-- =================================
	[K_USUARIO]						[INT]			NOT NULL,
	[K_TIPO_GRUPO_APROBADOR]		[INT]			NOT NULL,	
	[K_ESTATUS_GRUPO_APROBADOR]		[INT]			NOT NULL,
	-- =================================	
)ON [PRIMARY]	
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[GRUPO_APROBADOR]
	ADD CONSTRAINT [PK_GRUPO_APROBADOR]
		PRIMARY KEY CLUSTERED ([K_GRUPO_APROBADOR])
GO

-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[GRUPO_APROBADOR] ADD 
	CONSTRAINT [FK_GRUPO_APROBADOR_01]  
		FOREIGN KEY ([K_ESTATUS_GRUPO_APROBADOR]) 
		REFERENCES [dbo].[ESTATUS_GRUPO_APROBADOR] ([K_ESTATUS_GRUPO_APROBADOR]),
	CONSTRAINT [FK_GRUPO_APROBADOR_02]  
		FOREIGN KEY ([K_TIPO_GRUPO_APROBADOR]) 
		REFERENCES [dbo].[TIPO_GRUPO_APROBADOR] ([K_TIPO_GRUPO_APROBADOR])
	--CONSTRAINT [FK_GRUPO_APROBADOR_03]  
	--	FOREIGN KEY ([K_USUARIO]) 
	--	REFERENCES DATA_02.[dbo].[users_pearl] ([codigo])
GO


-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_GRUPO_APROBADOR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_GRUPO_APROBADOR]
GO


CREATE PROCEDURE [dbo].[PG_CI_GRUPO_APROBADOR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	-- ========================================
	@PP_K_GRUPO_APROBADOR		INT,
	@PP_D_GRUPO_APROBADOR		VARCHAR(100),
	@PP_S_GRUPO_APROBADOR		VARCHAR(10),
	@PP_K_USUARIO				INT,
	@PP_K_TIPO_GRUPO_APROBADOR	INT,
	@PP_K_ESTATUS_APROBADOR		INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_GRUPO_APROBADOR
							FROM	GRUPO_APROBADOR
							WHERE	K_GRUPO_APROBADOR=@PP_K_GRUPO_APROBADOR

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO GRUPO_APROBADOR	
			(	K_GRUPO_APROBADOR,				D_GRUPO_APROBADOR, 
				S_GRUPO_APROBADOR,				K_USUARIO,
				K_TIPO_GRUPO_APROBADOR,
				K_ESTATUS_GRUPO_APROBADOR				)		
		VALUES	
			(	@PP_K_GRUPO_APROBADOR,			@PP_D_GRUPO_APROBADOR,	
				@PP_S_GRUPO_APROBADOR,			@PP_K_USUARIO,
				@PP_K_TIPO_GRUPO_APROBADOR,
				@PP_K_ESTATUS_APROBADOR			)
	ELSE
		UPDATE	GRUPO_APROBADOR
		SET		D_GRUPO_APROBADOR			= @PP_D_GRUPO_APROBADOR,	
				S_GRUPO_APROBADOR			= @PP_S_GRUPO_APROBADOR,			
				K_USUARIO					= @PP_K_USUARIO,
				K_TIPO_GRUPO_APROBADOR		= @PP_K_TIPO_GRUPO_APROBADOR,
				K_ESTATUS_GRUPO_APROBADOR	= @PP_K_ESTATUS_APROBADOR	
		WHERE	K_GRUPO_APROBADOR=@PP_K_GRUPO_APROBADOR

	-- =========================================================
GO



-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- USE BD_GENERAL
-- ===================USUARIOS PARA DESCRIPCION DE PUESTO PARA PRUEBAS / SE HACE CON LOS NUMEORS DE RELOJ============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 1, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 13367, 1, 1 -- RH CREAR/MODIFICAR
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 2, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 13367, 2, 1 -- APROVAR GERENTES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 3, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 13367, 3, 1 -- NOTIFICAR

-- ===================USUARIOS PARA DESCRIPCION DE PUESTO GERENTES / SE HACE CON LOS NUMEORS DE RELOJ============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 4, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 22,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 5, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 52,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 6, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 67,	2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 7, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 181, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 8, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 1299, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 9, 'APROBADORES DESCRIPCION DE PUESTO',		'APROB_DP', 4475, 2,1
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 10, 'APROBADORES DESCRIPCION DE PUESTO',	'APROB_DP', 7945, 2,1

-- ===================USUARIOS AUTORIZADOS PARA SALIDA DE MQU EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 51, 'AUTORIZAR SALIDA MQU',					'AUT_SL_MQU', 144, 21, 0 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 52, 'AUTORIZAR SALIDA MQU',					'AUT_SL_MQU', 132, 21, 1 --TERESAJ

-- ===================ENVIAR CORREO PARA MFP DE ENTRADA DE PIELES EN PANTALLA FOLIOS============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 101, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 45, 41, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 102, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 56, 41, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 103, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 70, 41, 1 -- FERNANDOG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 104, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 87, 41, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 105, 'NOTIFICAR ENTRADA MFP',				'NOT_EN_MFP', 144, 41, 1 -- FEG

-- ===================USUARIOS PARA TRANSFERIR ORDEN COMPLETADA PANTALLA Transferencias============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 151, 'TRANSFERIR ORDEN',					'TRANS_ORD', 41, 61, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 152, 'TRANSFERIR ORDEN',					'TRANS_ORD', 45, 61, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 153, 'TRANSFERIR ORDEN',					'TRANS_ORD', 54, 61, 1 -- GILBERTOV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 154, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 61, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 155, 'TRANSFERIR ORDEN',					'TRANS_ORD', 63, 61, 1 -- LUISP
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 156, 'TRANSFERIR ORDEN',					'TRANS_ORD', 70, 61, 1 -- FERNANDOG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 157, 'TRANSFERIR ORDEN',					'TRANS_ORD', 72, 61, 1 -- ROXANAL
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 158, 'TRANSFERIR ORDEN',					'TRANS_ORD', 87, 61, 1 -- DIANAN
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 159, 'TRANSFERIR ORDEN',					'TRANS_ORD', 113, 61, 1 -- ERNESTOG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 160, 'TRANSFERIR ORDEN',					'TRANS_ORD', 114, 61, 1 -- JOSUEC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 161, 'TRANSFERIR ORDEN',					'TRANS_ORD', 138, 61, 1 -- RODOLFOC

-- ===================USUARIOS PARA TRANSFERIR ORDEN TX7 PANTALLA Transferencias============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 162, 'TRANSFERIR ORDEN',					'TRANS_ORD', 41, 62, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 163, 'TRANSFERIR ORDEN',					'TRANS_ORD', 45, 62, 1 -- PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 164, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 62, 1 -- MANUELG

-- ===================USUARIOS PARA TRANSFERIR LOTES NO COMPATIBLES PANTALLA Transferencias============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 165, 'TRANSFERIR ORDEN',					'TRANS_ORD', 56, 63, 1 -- MANUELG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 166, 'TRANSFERIR ORDEN',					'TRANS_ORD', 92, 63, 1 -- JOSES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 167, 'TRANSFERIR ORDEN',					'TRANS_ORD', 48, 63, 1 -- IVAND
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 168, 'TRANSFERIR ORDEN',					'TRANS_ORD', 47, 63, 1 -- MIGUELC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 169, 'TRANSFERIR ORDEN',					'TRANS_ORD', 86, 63, 1 -- JORGEO

-- ===================USUARIOS PARA MODIFICAR ESTATUS DEL REPORTE PANTALLA IncInsp============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 200, 'REPORTE INCOMING INSPECTION',			'RPT_INC_IN', 47, 81, 1 -- MIGUELC

-- ===================USUARIOS PARA SELECCIONAR TODOS LOS KITS PANTALLA frmKits============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 250, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 41, 101, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 251, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 68, 101, 1 -- ARMIDAH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 252, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 73, 101, 1 -- YAMILEXQ
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 253, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 64, 101, 1 -- LEONORH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 254, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 49, 101, 1 -- OSCART
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 255, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 44, 101, 1 -- GUILLERMOM
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 256, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 67, 101, 1 -- GASPARH

-- ===================USUARIOS PARA ABRIR LA ORDEN COMPLETADA PANTALLA frmKits============================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 257, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 41, 102, 1 -- RAFAELF
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 258, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 44, 102, 1 -- GUILLERMOM
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 259, 'PRODUCCION SELECCIONAR KITS',			'PRD_SL_KIT', 144, 102, 1 -- FEG

-- =============================================== -- ===============================================
-- ================================= GRUPOS APROBADORES PARA PO	================================== AX
-- =============================================== -- ===============================================
-- #6001- 'CREAR PO',		#6002- 'AUTORIZAR PO',		#6003- 'NOTIFICAR PO',		#6004- 'IMPRIMIR PO'
-- =================================			CREAR PO		   ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 260, 'CREAR PO',			'USR_IN_PO', 62,	6001, 1		-- PATY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 261, 'CREAR PO',			'USR_IN_PO', 115,	6001, 1		-- SONIA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 262, 'CREAR PO',			'USR_IN_PO', 121,	6001, 1		-- LUCY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 263, 'CREAR PO',			'USR_IN_PO', 125,	6001, 1		-- IRIS

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 264, 'CREAR PO',			'USR_IN_PO', 145,	6001, 1		-- DULCE

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 265, 'CREAR PO',			'USR_IN_PO', 41,	6001, 1		-- RAFA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 266, 'CREAR PO',			'USR_IN_PO', 42,	6001, 1		-- OMAR
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 267, 'CREAR PO',			'USR_IN_PO', 139,	6001, 1		-- AX
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 268, 'CREAR PO',			'USR_IN_PO', 144,	6001, 1		-- FEG

-- =================================	AUTORIZAR PO - GERENTES	  ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 269, 'AUTORIZAR PO',		'USR_UP_PO', 62,	6002, 1		-- PATY			RH / SEG / ENFER
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 270, 'AUTORIZAR PO',		'USR_UP_PO', 42,	6002, 1		-- OMAR			SIST/PROY
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 271, 'AUTORIZAR PO',		'USR_UP_PO', 44,	6002, 1		-- GUILLERMO	PROD / MTTO / ING
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 272, 'AUTORIZAR PO',		'USR_UP_PO', 47,	6002, 1		-- MIKE			QC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 273, 'AUTORIZAR PO',		'USR_UP_PO', 56,	6002, 1		-- MIGUELG		MATERIALES
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 274, 'AUTORIZAR PO',		'USR_UP_PO', 60,	6002, 1		-- ADRIANA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 275, 'AUTORIZAR PO',		'USR_UP_PO', 57,	6002, 1		-- FABIOLA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 276, 'AUTORIZAR PO',		'USR_UP_PO', 139,	6002, 1		-- AX			PRUEBAS

-- =================================			IMPRIMIR PO 	  ==================================
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 278, 'IMPRIMIR PO',			'USR_IM_PO', 57,	6004, 1		-- FABIOLA		FINANZAS
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 279, 'IMPRIMIR PO',			'USR_IM_PO', 139,	6004, 1		-- AX


--=========PARA CERRAR ORDEN PANTALLA FORMLOTS========================================
-- SELECT * FROM GRUPO_APROBADOR
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 301, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 144, 121, 1 -- FEG
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 302, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 41, 121, 1 --RAFA
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 303, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 44, 121, 1 --GUILLERMO
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 87, 121, 1 --DIANAN

EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 45, 121, 1 --PEDROV
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 67, 121, 1 --GASPARH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 68, 121, 1 --ARMIDAH
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 145, 121, 1 --DULCEC
EXECUTE [dbo].[PG_CI_GRUPO_APROBADOR] 0, 0, 304, 'PRD CERRAR ORDEN',					'PR_CER_ORD', 64, 121, 1 --LEONORH

/*
USE BD_GENERAL

SELECT * FROM GRUPO_APROBADOR WHERE D_GRUPO_APROBADOR = 'AUTORIZAR TRANSACCION'

select * from sistema_tag where d_sistema_tag = 'frmKits'
select * from SISTEMA_CONTROL
select * from SISTEMA_CONTROL_PERMISO WHERE K_SISTEMA_CONTROL = 50
SELECT * FROM USUARIO_PEARL WHERE D_USUARIO_PEARL LIKE 'CARL' --k_USUARIO_TIPO = 70 --K_USUARIO_PEARL IN (144,41,139)
SELECT * FROM USUARIO_TIPO

SELECT  K_USUARIO_TIPO AS TIPO ,* FROM USUARIO_PEARL 
WHERE K_USUARIO_TIPO IN (10, 40, 50) 
AND K_USUARIO_PEARL IN (SELECT K_USUARIO_PEARL FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 6)

SELECT * FROM USUARIO_PERMISOS WHERE K_SISTEMA_TAG = 60

--delete GRUPO_APROBADOR where k_GRUPO_APROBADOR IN (
														300,
														301,
														302,
														303,
														304 )
*/
GO
-- ===============================================
SET NOCOUNT OFF
-- ===============================================

GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
