-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		COT19
-- // MODULE:			COUNTRY
-- // OPERATION:		PROCEDIMIENTOS ESPECIFICOS
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX DE LA ROSA			
-- // CREATION DATE:	20190903
-- ////////////////////////////////////////////////////////////// 

USE [BD_GENERAL]
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> CARGA INICIAL
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_COUNTRY]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_COUNTRY]
GO


CREATE PROCEDURE [dbo].[PG_CI_COUNTRY]
	--@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ========================================
	@PP_K_COUNTRY				INT,			
	@PP_D_COUNTRY				VARCHAR(100),
	@PP_S_COUNTRY				VARCHAR(10),
	@PP_O_COUNTRY				INT,
	@PP_C_COUNTRY				VARCHAR(255),
	@PP_L_COUNTRY				INT,
	-- =========================================
	@PP_K_CONTINENTE			INT
AS
	
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_COUNTRY
							FROM	[COUNTRY]
							WHERE	K_COUNTRY=@PP_K_COUNTRY

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO [COUNTRY]	
			(	[K_COUNTRY], [D_COUNTRY],
				[S_COUNTRY], [O_COUNTRY],
				[C_COUNTRY], [L_COUNTRY],
				[K_CONTINENTE], 
			-- ============================================
				[K_USUARIO_ALTA], [F_ALTA], 
				[K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )		
		VALUES	
			(	@PP_K_COUNTRY, @PP_D_COUNTRY,
				@PP_S_COUNTRY, @PP_O_COUNTRY, 
				@PP_C_COUNTRY, @PP_L_COUNTRY,
				@PP_K_CONTINENTE,		
			-- ============================================
				@PP_K_USUARIO_ACCION, GETDATE(), 
				@PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL )							
	ELSE
		UPDATE	COUNTRY
		SET		
				[D_COUNTRY]				= @PP_D_COUNTRY,					
				[S_COUNTRY]				= @PP_S_COUNTRY,					
				[C_COUNTRY]				= @PP_C_COUNTRY,
				[K_CONTINENTE]			= @PP_K_CONTINENTE,
			-- ===========================
				[K_USUARIO_CAMBIO]			= @PP_K_USUARIO_ACCION, 
				[F_CAMBIO]					= GETDATE() 
		WHERE	K_COUNTRY=@PP_K_COUNTRY
	-- =========================================================
GO



-- ===============================================
SET NOCOUNT ON
-- ===============================================

-- //////////////////////////////////////////////////////////////
---	ÁFRICA
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 0, '(NO-COUNTRY)', '( N/CT )' , 1 ,														'(NO-COUNTRY)' , 0,0
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 101, 'REPÚBLICA DE ANGOLA', 'ANGOL' , 1 ,													'ANGOLA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 102, 'REPÚBLICA DEMOCRÁTICA Y POPULAR DE ARGELIA',										'ARGEL' , 0 , 'ARGELIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 104, 'REPÚBLICA DE BENÍN', 'BENÍN' , 1 ,													'BENÍN' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 105, 'REPÚBLICA DE BOTSWANA', 'BOTSW' , 1 ,												'BOTSWANA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 106, 'BURKINA FASO', 'BURKI' , 1 ,														'BURKINA FASO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 107, 'REPÚBLICA DE BURUNDI',		'BURUN' , 1 ,											'BURUNDI' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 108, 'REPÚBLICA DE CABO VERDE', 'CABO' , 1 ,												'CABO VERDE' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 109, 'REPÚBLICA DE CAMERÚN', 'CAMER' , 1 ,												'CAMERÚN' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 112, 'REPÚBLICA DE RUANDA', 'RUAND' , 1 ,													'RUANDA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 113, 'REPÚBLICA POPULAR DEL CONGO', 'PCONGO' , 1 ,										'REPÚBLICA POPULAR DEL CONGO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 114, 'REPÚBLICA DE COSTA DE MARFIL', 'CMARF' , 1 ,										'COSTA DE MARFIL' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 115, 'REPÚBLICA DE CHAD', 'CHAD' , 1 ,													'CHAD' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 116, 'REPÚBLICA DE DJIBOUTI', 'DJIBO' , 1 ,												'DJIBOUTI' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 117, 'REPÚBLICA ÁRABE DE EGIPTO', 'EGYP' , 1 ,											'EGIPTO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 118, 'ESTADO DE ERITREA', 'EERIT' , 1 ,													'ERITREA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 119, 'REPÚBLICA FEDERAL DEMOCRÁTICA DE ETIOPÍA', 'ETIOP' , 1 ,							'ETIOPÍA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 120, 'REPÚBLICA GABONESA', 'GABON' , 1 ,													'GABON' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 121, 'REPÚBLICA DE GAMBIA', 'GAMBI' , 1 ,													'GAMBIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 122, 'REPÚBLICA DE GHANA', 'GHANA' , 1 ,													'GHANA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 123, 'REPÚBLICA DE GUINEA', 'GUINE' , 1 ,													'GUINEA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 124, 'REPÚBLICA DE GUINEA BISSAU', 'GBISS' , 1 ,											'GUINEA BISSAU' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 125, 'REPÚBLICA DE GUINEA ECUATORIAL', 'GECUA' , 1 ,										'GUINEA ECUATORIAL' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 126, 'REPÚBLICA DE KENIA', 'KENIA' , 1 ,													'KENIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 127, 'REINO DE LESOTHO', 'LESOT' , 1 ,													'LESOTHO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 128, 'REPÚBLICA DE LIBERIA', 'LIBER' , 1 ,												'LIBERIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 129, 'LIBIA', 'LIBIA' , 1 ,																'LIBIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 130, 'REPÚBLICA DE MADAGASCAR', 'MADAG' , 1 ,												'MADAGASCAR' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 133, 'REPÚBLICA DE MALAWI', 'MALAW' , 1 ,													'MALAWI' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 134, 'REPÚBLICA DE MALÍ', 'MALÍ' , 1 ,													'MALÍ' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 135, 'REINO DE MARRUECOS', 'MARRU' , 1 ,													'MARRUECOS' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 136, 'REPÚBLICA DE MAURICIO', 'MAURI' , 1 ,												'MAURICIO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 137, 'REPÚBLICA ISLÁMICA DE MAURITANIA', 'MAURC' , 1 ,									'MAURITANIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 138, 'ISLAS ANGLONORMANDAS', 'ANGLO' , 1 ,												'ISLAS ANGLONORMANDAS' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 139, 'REPÚBLICA DE MOZAMBIQUE', 'MOZAM' , 1 ,												'MOZAMBIQUE' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 140, 'REPÚBLICA DE NAMIBIA', 'NAMIB' , 1 ,												'NAMIBIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 141, 'REPÚBLICA DE NÍGER', 'NÍGER' , 1 ,													'NÍGER' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 142, 'REPÚBLICA FEDERAL DE NIGERIA', 'NIGRIA' , 1 ,										'NIGERIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 143, 'REPÚBLICA CENTROAFRICANA', 'CAFRI' , 1 ,											'REPÚBLICA CENTROAFRICANA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 145, 'COLECTIVIDAD TERRITORIAL DE SAN PEDRO Y MIQUELÓN', 'SPEDR' , 1 ,					'SAN PEDRO Y MIQUELÓN' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 147, 'ISLA SANTA HELENA', 'ISELE' , 1 ,													'ISLA SANTA HELENA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 148, 'REPÚBLICA DEMOCRÁTICA DE SANTO TOME Y PRÍNCIPE', 'STYPR' , 1 ,						'SANTO TOME Y PRÍNCIPE' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 149, 'REPÚBLICA DE SENEGAL', 'SENEG' , 1 ,												'SENEGAL' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 150, 'REPÚBLICA DE ISLA SEYCHELLES', 'SEYCH' , 1 ,										'ISLA SEYCHELLES' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 151, 'REPÚBLICA DE SIERRA LEONA', 'SLEON' , 1 ,											'SIERRA LEONA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 152, 'UNIÓN DE LAS COMORAS', 'UCOMO' , 1 ,												'COMORAS' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 153, 'REPÚBLICA DE SOMALIA', 'SOMAL' , 1 ,												'SOMALIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 154, 'REPÚBLICA DE SUDÁFRICA', 'SUDÁF' , 1 ,												'SUDÁFRICA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 160, 'REINO DE SUAZILANDIA', 'RSUAZ' , 1 ,												'SUAZILANDIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 161, 'REPÚBLICA UNIDA DE TANZANIA', 'TANZA' , 1 ,											'TANZANIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 162, 'REPÚBLICA TOGOLESA', 'TOGOL' , 1 ,													'TOGO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 164, 'REPÚBLICA DE TÚNEZ', 'TÚNEZ' , 1 ,													'TÚNEZ' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 165, 'REPÚBLICA DE UGANDA', 'UGAND' , 1 ,													'UGANDA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 167, 'REPÚBLICA DE ZAMBIA', 'ZAMBI' , 1 ,													'ZAMBIA' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 168, 'REPÚBLICA DE ZIMBABWE', 'ZIMBA' , 1 ,												'ZIMBABWE' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 169, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'DCONGO' , 1 ,									'REPÚBLICA DEMOCRÁTICA DEL CONGO' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 170, 'REPÚBLICA ÁRABE SAHARAUI DEMOCRÁTICA', 'ARABE' , 1 ,								'SAHARAUI' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 171, 'REPÚBLICA DE SUDÁN', 'SUDÁN' , 1 ,													'SUDÁN' , 0,100
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 172, 'REPÚBLICA DE SUDÁN DEL SUR', 'SUDSU' , 1 ,											'SUDÁN DEL SUR' , 0,100
-- //////////////////////////////////////////////////////////////
---	AMÉRICA
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 201, 'ANGUILA', 'ANGUI' , 1 ,																'ANGUILA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 202, 'ANTIGUA Y BARBUDA', 'AYBAR' , 1 ,													'ANTIGUA Y BARBUDA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 204, 'REPÚBLICA ARGENTINA', 'ARGEN' , 1 ,													'ARGENTINA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 205, 'ARUBA', 'ARUBA' , 1 ,																'ARUBA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 206, 'COMMONWEALTH DE LAS BAHAMAS', 'BAHAM' , 1 ,											'BAHAMAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 207, 'BARBADOS', 'BARBA' , 1 ,															'BARBADOS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 208, 'BELICE', 'BELIC' , 1 ,																'BELICE' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 209, 'ISLAS BERMUDAS', 'IBERM' , 1 ,														'BERMUDAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 210, 'REPÚBLICA DE BOLIVIA', 'BOLIV' , 1 ,												'BOLIVIA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 211, 'REPÚBLICA FEDERATIVA DE BRASIL', 'BRASI' , 1 ,										'BRASIL' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 212, 'ISLAS CAIMÁN', 'ICAIM' , 1 ,														'ISLAS CAIMÁN' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 213, 'CANADÁ', 'CANAD' , 1 ,																'CANADÁ' , 1,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 214, 'REPÚBLICA DE COLOMBIA', 'COLOM' , 1 ,												'COLOMBIA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 215, 'REPÚBLICA DE COSTA RICA', 'CRICA' , 1 ,												'COSTA RICA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 216, 'REPÚBLICA DE CUBA', 'CUBA' , 1 ,													'CUBA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 217, 'REPÚBLICA DE CHILE', 'CHILE' , 1 ,													'CHILE' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 218, 'COMMONWEALTH DE DOMINICA', 'DMNCA' , 1 ,											'DOMINICA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 219, 'REPÚBLICA DE ECUADOR', 'ECUAD' , 1 ,												'ECUADOR' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 220, 'REPÚBLICA DE EL SALVADOR', 'SALVA' , 1 ,											'EL SALVADOR' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 221, 'ESTADOS UNIDOS DE AMÉRICA', 'USA' , 1 ,												'ESTADOS UNIDOS DE AMÉRICA' , 1,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 222, 'GRANADA', 'GRANA' , 1 ,																'GRANADA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 223, 'GROENLANDIA', 'GROEN' , 1 ,															'GROENLANDIA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 224, 'DEPARTAMENTO DE GUADALUPE', 'GDLPE' , 1 ,											'GUADALUPE' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 225, 'REPÚBLICA DE GUATEMALA', 'GUATE' , 1 ,												'GUATEMALA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 226, 'REPÚBLICA COOPERATIVA DE GUYANA', 'GUYAN' , 1 ,										'GUYANA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 227, 'GUAYANA FRANCESA', 'GFRAN' , 1 ,													'GUAYANA FRANCESA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 228, 'REPÚBLICA DE HAITÍ', 'HAITÍ' , 1 ,													'HAITÍ' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 229, 'REPÚBLICA DE HONDURAS', 'HONDU' , 1 ,												'HONDURAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 230, 'JAMAICA', 'JAMAI' , 1 ,																'JAMAICA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 231, 'ISLAS MALVINAS', 'IMALV' , 1 ,														'ISLAS MALVINAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 233, 'ISLA DE MONTSERRAT', 'IMONT' , 1 ,													'ISLA DE MONTSERRAT' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 234, 'REPÚBLICA DE NICARAGUA', 'NICAR' , 1 ,												'NICARAGUA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 235, 'REPÚBLICA DE PANAMÁ', 'PANAM' , 1 ,													'PANAMÁ' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 236, 'REPÚBLICA DE PARAGUAY', 'PARAG' , 1 ,												'PARAGUAY' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 237, 'REPÚBLICA DE PERÚ', 'PERÚ' , 1 ,													'PERÚ' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 238, 'ESTADO LIBRE ASOCIADO DE PUERTO RICO', 'PRICO' , 1 ,								'PUERTO RICO' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 239, 'REPÚBLICA DOMINICANA', 'RDOMI' , 1 ,												'REPÚBLICA DOMINICANA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 240, 'FEDERACIÓN DE SAN CRISTÓBAL Y NIEVES', 'SCYNI' , 1 ,								'SAN CRISTÓBAL Y NIEVES' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 241, 'ISLAS DE MAN', 'IMAN' , 1 ,															'ISLAS DE MAN' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 242, 'SAN VICENTE Y LAS GRANADINAS', 'SVYGR' , 1 ,										'SAN VICENTE Y LAS GRANADINAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 243, 'SANTA LUCÍA', 'STALU' , 1 ,															'SANTA LUCÍA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 244, 'REPÚBLICA DE SURINAM', 'SURIN' , 1 ,												'SURINAM' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 245, 'REPÚBLICA DE TRINIDAD Y TOBAGO', 'TYTOB' , 1 ,										'TRINIDAD Y TOBAGO' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 246, 'ISLAS TURCAS Y CAICOS', 'ITURC' , 1 ,												'ISLAS TURCAS Y CAICOS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 247, 'REPÚBLICA ORIENTAL DEL URUGUAY', 'URUGU' , 1 ,										'URUGUAY' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 248, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'IVÍES' , 1 ,								'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 249, 'ISLAS VÍRGENES BRITÁNICAS', 'IVÍBR' , 1 ,											'ISLAS VÍRGENES BRITÁNICAS' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 250, 'REPÚBLICA BOLIVIANA DE VENEZUELA', 'VENEZ' , 1 , '									VENEZUELA' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 251, 'CURAZAO', 'CURAZ' , 1 ,																'CURAZAO' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 252, 'ISLA DE SAINT MARTEEN', 'ISTMA' , 1 ,												'ISLA DE SAINT MARTEEN' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 253, 'BONAIRE, SAN EUSTAQUIO, SABA', 'BEUST' , 1 ,										'BONAIRE' , 0,200
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 260, 'ESTADOS UNIDOS MEXICANOS', 'MEX' , 1 ,												'MÉXICO' , 1,200
-- //////////////////////////////////////////////////////////////
---	ASIA
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 301, 'ESTADO ISLÁMICO DE AFGANISTÁN', 'AFGAN' , 1 ,										'AFGANISTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 302, 'REINO DE ARABIA SAUDITA', 'ASAUD' , 1 ,												'ARABIA SAUDITA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 303, 'REPÚBLICA DE ARMENIA', 'ARMEN' , 1 ,												'ARMENIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 304, 'REPÚBLICA DE AZERBAIYÁN', 'AZERB' , 1 ,												'AZERBAIYÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 305, 'REINO DE BAHRÉIN', 'RBAHR' , 1 ,													'BAHRÉIN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 306, 'REPÚBLICA POPULAR DE BANGLADESH', 'BANGL' , 1 ,										'BANGLADESH' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 307, 'REINO DE BHUTAN', 'BHUTA' , 1 ,														'BHUTAN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 308, 'ESTADO DE BRUNEI DARUSSALAM', 'BRUNE' , 1 ,											'BRUNEI DARUSSALAM' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 309, 'REINO DE CAMBOYA', 'CAMBO' , 1 ,													'CAMBOYA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 312, 'REPÚBLICA POPULAR DEMOCRÁTICA DE COREA', 'RCORE' , 1 ,								'COREA DEL NORTE' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 313, 'REPÚBLICA DE COREA', 'COREA' , 1 ,													'COREA DEL SUR' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 315, 'REPÚBLICA POPULAR CHINA','CHINA' , 1 ,												'CHINA' , 1,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 316, 'TAIWÁN', 'TAIWA' , 1 ,																'TAIWÁN' , 1,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 318, 'REPÚBLICA DE CHIPRE', 'CHIPR' , 1 ,													'CHIPRE' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 321, 'EMIRATOS ÁRABES UNIDOS', 'EAUNI' , 1 ,												'EMIRATOS ÁRABES UNIDOS' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 322, 'REPÚBLICA DE FILIPINAS', 'FILIP' , 1 ,												'FILIPINAS' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 323, 'REPÚBLICA DE GEORGIA', 'GEORG' , 1 ,												'GEORGIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 325, 'REPÚBLICA DE LA INDIA', 'INDIA' , 1 ,												'INDIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 326, 'REPÚBLICA DE INDONESIA', 'INDON' , 1 ,												'INDONESIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 327, 'REPÚBLICA ISLÁMICA DE IRÁN', 'IRÁN' , 1 ,											'IRÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 328, 'REPÚBLICA DE IRAQ', 'IRAQ' , 1 ,													'IRAQ' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 329, 'ESTADO DE ISRAEL', 'ISRAE' , 1 ,													'ISRAEL' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 330, 'ESTADO DE JAPÓN', 'JAPÓN' , 1 ,														'JAPÓN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 331, 'REINO HACHEMÍ DE JORDANIA', 'JORDA' , 1 ,											'JORDANIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 332, 'REPÚBLICA DE KAZAJSTÁN', 'KAZAJ' , 1 ,												'KAZAJSTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 333, 'REPÚBLICA KIRGUISA', 'KIRGU' , 1 ,													'KIRGUISA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 334, 'ESTADO DE KUWAIT', 'KUWAI' , 1 ,													'KUWAIT' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 335, 'REPÚBLICA LIBANESA', 'LIBAN' , 1 ,													'REPÚBLICA LIBANESA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 337, 'MALASIA', 'MALAS' , 1 ,																'MALASIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 338, 'REPÚBLICA DE MALDIVAS', 'MALDI' , 1 ,												'MALDIVAS' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 339, 'MONGOLIA', 'MONGOL' , 1 ,															'MONGOLIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 340, 'UNIÓN DE MYANMAR', 'MYANM' , 1 ,													'MYANMAR' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 341, 'REPÚBLICA FEDERAL DEMOCRÁTICA DE NEPAL','NEPAL' , 1 ,								'NEPAL' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 342, 'SULTANATO DE OMÁN', 'OMÁN' , 1 ,													'OMÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 343, 'REPÚBLICA ISLÁMICA DE PAKISTÁN', 'PAKIS' , 1 ,										'PAKISTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 344, 'ESTADO DE QATAR', 'QATAR' , 1 ,														'QATAR' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 345, 'REPÚBLICA DEMOCRÁTICA POPULAR DE LAOS', 'LAOS' , 1 ,								'LAOS' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 346, 'REPÚBLICA DE SINGAPUR', 'SINGA' , 1 ,												'SINGAPUR' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 347, 'REPÚBLICA ÁRABE SIRIA', 'SIRIA' , 1 ,												'SIRIA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 348, 'REPÚBLICA DEMOCRÁTICA SOCIALISTA SRI LANKA','SRILA' , 1 ,							'SRI LANKA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 349, 'REINO DE TAILANDIA', 'TAILA' , 1 ,													'TAILANDIA' , 1,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 350, 'REPÚBLICA DE TAYIKISTÁN', 'TAYIK' , 1 ,												'TAYIKISTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 351, 'TURKMENISTÁN', 'TURKE' , 1 ,														'TURKMENISTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 352, 'REPÚBLICA DE TURQUÍA', 'TURQU' , 1 ,												'TURQUÍA' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 353, 'REPÚBLICA DE UZBEKISTÁN', 'UZBEK' , 1 ,												'UZBEKISTÁN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 354, 'REPÚBLICA SOCIALISTA DE VIETNAM', 'VIETN' , 1 ,										'VIETNAM' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 355, 'REPÚBLICA DE YEMEN', 'YEMEN' , 1 ,													'YEMEN' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 356, 'REPÚBLICA DE PALAOS', 'PALAO' , 1 ,													'PALAOS' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 357, 'REPÚBLICA DEMOCRÁTICA DE TIMOR ORIENTAL', 'TIMOR' , 1 ,								'TIMOR ORIENTAL' , 0,300
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 358, 'ESTADO DE PALESTINA', 'PALES' , 1 ,													'PALESTINA' , 0,300
-- //////////////////////////////////////////////////////////////
---	EUROPA
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 401, 'REPÚBLICA DE ALBANIA', 'ALBAN' , 1 ,												'ALBANIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 402, 'REPÚBLICA FEDERAL DE ALEMANIA', 'ALEMA' , 1 ,										'ALEMANIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 403, 'PRINCIPADO DE ANDORRA', 'ANDOR' , 1 ,												'ANDORRA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 405, 'REPÚBLICA DE AUSTRIA', 'AUSTR' , 1 ,												'AUSTRIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 407, 'REPÚBLICA DE BIELORRUSIA', 'BIELO' , 1 ,											'BIELORRUSIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 408, 'REINO DE BÉLGICA', 'BELGI' , 1 ,													'BÉLGICA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 409, 'BOSNIA Y HERZEGOVINA', 'BSNHE' , 1 ,												'BOSNIA Y HERZEGOVINA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 410, 'REPÚBLICA DE BULGARIA', 'BULGA' , 1 ,												'BULGARIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 411, 'REPÚBLICA DE CROACIA', 'CROAC' , 1 ,												'CROACIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 412, 'REINO DE DINAMARCA', 'DINAM' , 1 ,													'DINAMARCA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 413, 'REPÚBLICA ESLOVACA', 'SLVAC' , 1 ,													'ESLOVAQUIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 414, 'REPÚBLICA DE ESLOVENIA', 'SLOVN' , 1 ,												'ESLOVENIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 415, 'REINO DE ESPAÑA', 'ESPAÑ' , 1 ,														'ESPAÑA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 416, 'REPÚBLICA DE ESTONIA', 'ESTON' , 1 ,												'ESTONIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 417, 'ISLAS FEROE', 'FEROE' , 1 ,															'ISLAS FEROE' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 418, 'REPÚBLICA DE FINLANDIA', 'FINLA' , 1 ,												'FINLANDIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 419, 'REPÚBLICA FRANCESA', 'FRANC' , 1 ,													'FRANCIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 420, 'GIBRALTAR', 'GIBRA' , 1 ,															'GIBRALTAR' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 421, 'REPÚBLICA HELÉNICA', 'HELEN' , 1 ,													'GRECIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 422, 'REPÚBLICA DE HUNGRÍA', 'HUNGR' , 1 ,												'HUNGRÍA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 423, 'REPÚBLICA DE IRLANDA', 'IRLAN' , 1 ,												'IRLANDA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 424, 'REPÚBLICA DE ISLANDIA', 'ISLAN' , 1 ,												'ISLANDIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 425, 'REPÚBLICA ITALIANA', 'ITALI' , 1 ,													'ITALIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 426, 'REPÚBLICA DE LETONIA', 'LETON' , 1 ,												'LETONIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 427, 'PRINCIPADO DE LIECHTENSTEIN', 'LIECH' , 1 ,											'LIECHTENSTEIN' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 428, 'REPÚBLICA DE LITUANIA', 'LITUA' , 1 ,												'LITUANIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 429, 'GRAN DUCADO DE LUXEMBURGO', 'LUXEM' , 1 ,											'LUXEMBURGO' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 430, 'ANTIGUA REPÚBLICA YUGOSLAVA DE MACEDONIA', 'MACED' , 1 ,							'MACEDONIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 431, 'REPÚBLICA DE MALTA', 'MALTA' , 1 ,													'MALTA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 433, 'REPÚBLICA DE MOLDAVIA', 'MOLDA' , 1 ,												'MOLDAVIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 434, 'PRINCIPADO DE MÓNACO', 'MÓNAC' , 1 ,												'MÓNACO' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 435, 'REINO DE NORUEGA', 'NORUE' , 1 ,													'NORUEGA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 436, 'REINO DE LOS PAÍSES BAJOS', 'PBAJO' , 1 ,											'PAÍSES BAJOS' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 437, 'REPÚBLICA DE POLONIA', 'POLON' , 1 ,												'POLONIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 438, 'REPÚBLICA PORTUGUESA', 'PORTU' , 1 ,												'PORTUGAL' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 439, 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA', 'RUNID' , 1 ,								'GRAN BRETAÑA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 440, 'REPÚBLICA CHECA', 'CHECA' , 1 ,														'REPÚBLICA CHECA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 441, 'RUMANIA', 'RUMAN' , 1 ,																'RUMANIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 442, 'FEDERACIÓN DE RUSIA', 'RUSIA' , 1 ,													'RUSIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 443, 'REPÚBLICA DE SAN MARINO', 'SMARI' , 1 ,												'SAN MARINO' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 444, 'ESTADO DE LA CIUDAD DEL VATICANO', 'VATIC' , 1 ,									'VATICANO' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 445, 'REINO DE SUECIA', 'SUECI' , 1 ,														'SUECIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 446, 'CONFEDERACIÓN SUIZA', 'SUIZA' , 1 ,													'SUIZA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 447, 'UCRANIA', 'UCRAN' , 1 ,																'UCRANIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 452, 'REPÚBLICA DE SERBIA', 'SERBI' , 1 ,													'SERBIA' , 0,400
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 453, 'REPÚBLICA DE MONTENEGRO', 'MONTE' , 1 ,												'MONTENEGRO' , 0,400
-- //////////////////////////////////////////////////////////////
---	OCEANÍA
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 501, 'COMMONWEALTH DE AUSTRALIA', 'ASTRL' , 1 ,											'AUSTRALIA' , 1,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 503, 'ISLAS COOK', 'ICOOK' , 1 ,															'ISLAS COOK' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 505, 'GUAM', 'GUAM' , 1 ,																	'GUAM' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 507, 'REPÚBLICA DE KIRIBATI', 'KIRIB' , 1 ,												'KIRIBATI' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 512, 'ISLAS MARIANAS DEL NORTE', 'IMARN' , 1 ,											'ISLAS MARIANAS DEL NORTE' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 513, 'REPÚBLICA DE LAS ISLAS MARSHAL', 'IMARS' , 1 ,										'ISLAS MARSHAL' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 514, 'ESTADOS FEDERADOS DE MICRONESIA', 'EFMIC' , 1 ,										'MICRONESIA' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 516, 'REPÚBLICA DE NAURU', 'NAURU' , 1 ,													'NAURU' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 517, 'NIUE', 'NIUE' , 1 ,																	'NIUE' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 520, 'NUEVA ZELANDA', 'NVAZE' , 1 ,														'NUEVA ZELANDA' , 1,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 522, 'ISLA WAKE', 'IWAKE' , 1 ,															'ISLA WAKE' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 523, 'ESTADO INDEPENDIENTE DE PAPÚA NUEVA GUINEA', 'NVAGU' , 1 ,							'PAPÚA NUEVA GUINEA' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 524, 'ISLAS PITCAIRN', 'IPITC' , 1 ,														'ISLAS PITCAIRN' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 526, 'ISLAS SALOMÓN', 'ISALO' , 1 ,														'ISLAS SALOMÓN' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 527, 'ESTADO INDEPENDIENTE DE SAMOA', 'SAMOA' , 1 ,										'SAMOA' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 528, 'SAMOA AMERICANA', 'SAMAM' , 1 ,														'SAMOA AMERICANA' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 530, 'TOKELAU', 'TOKEL' , 1 ,																'TOKELAU' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 531, 'REINO DE TONGA', 'TONGA' , 1 ,														'TONGA' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 532, 'TUVALU', 'TUVAL' , 1 ,																'TUVALU' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 533, 'REPÚBLICA DE VANUATU', 'VANUA' , 1 ,												'VANUATU' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 534, 'TERRITORIO DE LAS ISLAS WALLI', 'IWALL' , 1 ,										'WALLI' , 0,500
EXECUTE [DBO].[PG_CI_COUNTRY] 0, 139, 535, 'REPÚBLICA DE LAS ISLAS FIJI', 'IFIJI' , 1 ,											'FIJI' , 0,500



GO


-- ===============================================
SET NOCOUNT OFF
-- ===============================================
GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
